# web_app/pages/2_Machine_learning_for_XAS.py
from __future__ import annotations

import csv
import io
import json
import math
import re
import sys
import zipfile
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import streamlit as st

try:
    import pandas as pd
except Exception:
    pd = None

try:
    from sklearn.decomposition import PCA
    from sklearn.dummy import DummyClassifier, DummyRegressor
    from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
    from sklearn.linear_model import LogisticRegression, Ridge
    from sklearn.metrics import balanced_accuracy_score, f1_score, mean_absolute_error, mean_squared_error, r2_score
    from sklearn.model_selection import KFold, StratifiedKFold, cross_validate, learning_curve, train_test_split
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.svm import SVC, SVR
    SKLEARN_AVAILABLE = True
    SKLEARN_IMPORT_ERROR = None
except Exception as exc:
    SKLEARN_AVAILABLE = False
    SKLEARN_IMPORT_ERROR = exc

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

ML_PAGE_UPDATE_TAG = "v39_2026-07-02_restore_training_curve_no_magic_dump"
ISAAC_PORTAL_URL = "https://isaac.slac.stanford.edu/portal/"
ENERGY_NAMES = ("energy", "incident_energy", "photon_energy", "mono_energy", "e0", "energy_ev", "e_ev")
ENERGY_UNITS = ("ev", "electronvolt", "electron_volt", "kev")
SIGNAL_NAMES = ("absorption", "absorbance", "mu", "xanes", "xas", "tey", "tfy", "pfy", "herfd", "intensity", "fluorescence", "delta_absorption")
EDGE_WINDOWS = [("C", "K", 260, 330), ("O", "K", 500, 560), ("Cu", "L", 920, 970), ("Ni", "L", 830, 890), ("Cu", "K", 8850, 9100), ("Ni", "K", 8200, 8500), ("Ir", "L3", 11100, 11350), ("Pt", "L3", 11400, 11650), ("Au", "L3", 11800, 12080)]

st.set_page_config(page_title="CO2RR XAS Agent | Machine learning for XAS", layout="wide")
st.title("Agentic machine learning for XAS")
st.caption(f"Update tag: `{ML_PAGE_UPDATE_TAG}`")
st.markdown(f"""
**Goal.** Build an agent-assisted workflow that turns ISAAC-format XAS records into validated spectral datasets, model inputs, trained ML models, performance diagnostics, training curves, and suggested next actions for CO2RR catalyst interpretation.

**Data source.** Upload ISAAC record JSON files from the [ISAAC portal]({ISAAC_PORTAL_URL}) or ISAAC-compatible records generated by this XAS agent. The app validates spectral axes/channels before ML.
""".strip())


def safe_str(x: Any) -> str:
    return "" if x is None else str(x)


def lower(x: Any) -> str:
    return safe_str(x).strip().lower()


def is_number(x: Any) -> bool:
    try:
        return math.isfinite(float(x))
    except Exception:
        return False


def integrate(y: np.ndarray, x: np.ndarray) -> float:
    if hasattr(np, "trapezoid"):
        return float(np.trapezoid(y, x))
    return float(np.trapz(y, x))


def as_array(values: Any) -> Optional[np.ndarray]:
    if values is None:
        return None
    try:
        out = np.asarray(values, dtype=float)
    except Exception:
        return None
    if out.ndim != 1 or out.size == 0 or not np.all(np.isfinite(out)):
        return None
    return out


def get_path(data: Dict[str, Any], dotted: str) -> Any:
    node: Any = data
    for part in dotted.split("."):
        if isinstance(node, dict) and part in node:
            node = node[part]
        else:
            return None
    return node


def flatten_scalars(data: Any, prefix: str = "", depth: int = 5) -> Dict[str, Any]:
    if depth < 0:
        return {}
    out: Dict[str, Any] = {}
    if isinstance(data, dict):
        for key, value in data.items():
            if str(key).startswith("_"):
                continue
            child = f"{prefix}.{key}" if prefix else str(key)
            out.update(flatten_scalars(value, child, depth - 1))
    elif isinstance(data, list):
        if len(data) <= 8 and all(not isinstance(v, (dict, list)) for v in data):
            out[prefix] = ", ".join(safe_str(v) for v in data)
    elif isinstance(data, (str, int, float, bool)) or data is None:
        out[prefix] = data
    return out


def find_first_key(data: Any, names: Sequence[str], depth: int = 6) -> Any:
    keys = {lower(k) for k in names}
    if depth < 0:
        return None
    if isinstance(data, dict):
        for key, value in data.items():
            if lower(key) in keys and not isinstance(value, (dict, list)):
                return value
        for value in data.values():
            found = find_first_key(value, names, depth - 1)
            if found not in [None, ""]:
                return found
    elif isinstance(data, list) and len(data) <= 30:
        for value in data:
            found = find_first_key(value, names, depth - 1)
            if found not in [None, ""]:
                return found
    return None


def descriptor_values(record: Dict[str, Any]) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for output in (record.get("descriptors") or {}).get("outputs") or []:
        label = output.get("label") or output.get("name") or "descriptor_output"
        for desc in output.get("descriptors") or []:
            name = desc.get("name")
            if name:
                out[f"descriptors.{name}"] = desc.get("value")
                out[f"descriptors.{label}.{name}"] = desc.get("value")
    return out


def canonical_element(x: Any) -> str:
    tokens = re.findall(r"[A-Za-z]{1,2}", safe_str(x))
    if not tokens:
        return ""
    token = tokens[0]
    return token.upper() if len(token) == 1 else token.capitalize()


def canonical_edge(x: Any) -> str:
    text = safe_str(x).upper()
    for pattern, prefix in [(r"L\s*([1-3])", "L"), (r"M\s*([1-5])", "M")]:
        match = re.search(pattern, text)
        if match:
            return prefix + match.group(1)
    match = re.search(r"\b(K|L|M|N|O)\b", text)
    return match.group(1) if match else ""


def infer_edge(x: Optional[np.ndarray]) -> Tuple[str, str, str]:
    if x is None or not x.size:
        return "unknown", "unknown", "not inferred"
    xmin, xmax = float(np.min(x)), float(np.max(x))
    mid = 0.5 * (xmin + xmax)
    for el, edge, lo, hi in EDGE_WINDOWS:
        if lo <= mid <= hi or xmin <= lo <= xmax or xmin <= hi <= xmax:
            return el, edge, "inferred from energy range"
    return "unknown", "unknown", "not inferred"


def absorber_edge(record: Dict[str, Any], x: Optional[np.ndarray]) -> Tuple[str, str, str]:
    raw_abs = get_path(record, "system.absorber") or get_path(record, "system.configuration.absorber") or get_path(record, "measurement.absorber") or find_first_key(record, ["absorber", "absorbing_element", "absorber_element"])
    raw_edge = get_path(record, "system.edge") or get_path(record, "system.configuration.edge") or get_path(record, "measurement.edge") or find_first_key(record, ["edge", "absorption_edge"])
    abs_el = canonical_element(raw_abs)
    edge = canonical_edge(raw_edge)
    if abs_el and edge:
        return abs_el, edge, "metadata"
    inferred_abs, inferred_edge, source = infer_edge(x)
    return abs_el or inferred_abs, edge or inferred_edge, source


def edge_group(absorber: str, edge: str) -> str:
    if not absorber or absorber == "unknown" or not edge or edge == "unknown":
        return "Unknown absorber/edge"
    return f"{absorber} {edge}-edge"


def classify_series(x_name: str, x_unit: str, y_name: str) -> Tuple[bool, str, str]:
    xn, xu, yn = lower(x_name), lower(x_unit), lower(y_name)
    if xn in {"q", "qz"} or "angstrom^-1" in xu or "1/angstrom" in xu:
        return False, "not_xas_scattering", "x-axis is q/scattering vector"
    has_energy_x = any(k in xn for k in ENERGY_NAMES) or xn in {"e", "energy_ev"}
    has_energy_unit = any(u == xu or u in xu for u in ENERGY_UNITS)
    has_signal = any(k in yn for k in SIGNAL_NAMES)
    if has_energy_x and has_energy_unit and has_signal:
        return True, "xas_like", "energy-axis XAS/XANES-like spectrum"
    if has_energy_x and has_energy_unit:
        return True, "xas_like_uncertain_y", "energy-axis spectrum; y name is not standard XAS"
    return False, "not_xas_unknown_axis", "no incident-energy x-axis with eV/keV units"


def read_records(files: Sequence[Any]) -> List[Tuple[str, Dict[str, Any]]]:
    records: List[Tuple[str, Dict[str, Any]]] = []
    for uploaded in files or []:
        name = getattr(uploaded, "name", "uploaded")
        payload = uploaded.getvalue()
        if name.lower().endswith(".zip"):
            with zipfile.ZipFile(io.BytesIO(payload)) as zf:
                for member in sorted(zf.namelist()):
                    if not member.lower().endswith(".json") or member.endswith("/"):
                        continue
                    try:
                        data = json.loads(zf.read(member).decode("utf-8"))
                    except Exception:
                        continue
                    if isinstance(data, dict):
                        records.append((member, data))
        elif name.lower().endswith(".json"):
            data = json.loads(payload.decode("utf-8"))
            if isinstance(data, dict):
                records.append((name, data))
    return records


def choose_channel(channels: Sequence[Dict[str, Any]]) -> Dict[str, Any]:
    if not channels:
        return {}
    for channel in channels:
        if lower(channel.get("role")) == "primary_signal":
            return channel
    for channel in channels:
        if any(token in lower(channel.get("name")) for token in SIGNAL_NAMES):
            return channel
    return channels[0]


def make_row(source: str, record: Dict[str, Any], series_id: str, x: Optional[np.ndarray], y: Optional[np.ndarray], x_name: str, x_unit: str, y_name: str, y_unit: str) -> Dict[str, Any]:
    absorber, edge, edge_source = absorber_edge(record, x)
    group = edge_group(absorber, edge)
    if x is None or y is None or x.size != y.size:
        is_xas, classification, reason = False, "not_plottable_invalid_xy", "missing/non-numeric x or y, or length mismatch"
    else:
        is_xas, classification, reason = classify_series(x_name, x_unit, y_name)
    metadata = {**flatten_scalars(record), **descriptor_values(record), "series.series_id": series_id, "series.x_name": x_name, "series.x_unit": x_unit, "series.y_name": y_name, "series.y_unit": y_unit, "derived.absorber": absorber, "derived.edge": edge, "derived.edge_group": group, "derived.n_points": int(x.size if x is not None else 0)}
    return {"source_name": source, "record_id": record.get("record_id"), "series_id": series_id, "technique": get_path(record, "system.technique") or get_path(record, "system.configuration.technique"), "formula": get_path(record, "sample.material.formula") or get_path(record, "sample.material.name"), "absorber": absorber, "edge": edge, "edge_group": group, "edge_source": edge_source, "x_name": x_name, "x_unit": x_unit, "y_name": y_name, "y_unit": y_unit, "n_points": int(x.size if x is not None else 0), "is_xas": is_xas, "classification": classification, "reason": reason, "record": record, "metadata": metadata, "x": x, "y": y}


def rows_from_records(records: Sequence[Tuple[str, Dict[str, Any]]]) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for source, record in records:
        added = False
        for i, series in enumerate((record.get("measurement") or {}).get("series") or []):
            xobj = (series.get("independent_variables") or [{}])[0]
            yobj = choose_channel(series.get("channels") or [])
            rows.append(make_row(source, record, safe_str(series.get("series_id")) or f"series_{i}", as_array(xobj.get("values")), as_array(yobj.get("values")), safe_str(xobj.get("name")), safe_str(xobj.get("unit")), safe_str(yobj.get("name")), safe_str(yobj.get("unit"))))
            added = True
        for i, out in enumerate((record.get("descriptors") or {}).get("outputs") or []):
            x = as_array(out.get("energy") or out.get("energy_eV") or out.get("x") or out.get("grid"))
            y = as_array(out.get("mu") or out.get("absorption") or out.get("intensity") or out.get("y") or out.get("values"))
            if x is not None and y is not None and x.size == y.size:
                rows.append(make_row(source, record, safe_str(out.get("label") or out.get("name") or f"descriptor_output_{i}"), x, y, "energy", "eV", safe_str(out.get("channel") or out.get("name") or "absorption"), safe_str(out.get("unit") or "a.u.")))
                added = True
        if not added:
            rows.append(make_row(source, record, "", None, None, "", "", "", ""))
    return rows


def summary_table(rows: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    keys = ["source_name", "record_id", "series_id", "technique", "formula", "absorber", "edge", "edge_group", "edge_source", "x_name", "x_unit", "y_name", "y_unit", "n_points", "is_xas", "classification", "reason"]
    return [{key: row.get(key) for key in keys} for row in rows]


def rows_to_csv(rows: Sequence[Dict[str, Any]]) -> str:
    if not rows:
        return ""
    out = io.StringIO()
    writer = csv.DictWriter(out, fieldnames=list(rows[0].keys()))
    writer.writeheader()
    writer.writerows(rows)
    return out.getvalue()


def minmax(y: np.ndarray) -> np.ndarray:
    span = float(np.max(y) - np.min(y))
    return np.zeros_like(y) if span == 0 else (y - float(np.min(y))) / span


def target_value(row: Dict[str, Any], path: str) -> Any:
    if path.startswith(("derived.", "series.", "descriptors.")):
        return (row.get("metadata") or {}).get(path)
    value = get_path(row.get("record") or {}, path)
    if value is not None:
        return value
    return (row.get("metadata") or {}).get(path)


def label_fields(rows: Sequence[Dict[str, Any]]) -> List[str]:
    preferred = ["sample.material.formula", "sample.material.name", "derived.absorber", "derived.edge", "derived.edge_group", "system.technique", "source_type", "record_domain"]
    keys = set()
    for row in rows:
        for key, value in (row.get("metadata") or {}).items():
            if value is not None and not (isinstance(value, str) and len(value) > 160):
                keys.add(key)
    return [key for key in preferred if key in keys] + sorted(keys - set(preferred))


def feature_matrix(rows: Sequence[Dict[str, Any]], target: str, kinds: Sequence[str], norm: str, n_grid: int):
    valid = [row for row in rows if row.get("x") is not None and row.get("y") is not None and row.get("n_points", 0) >= 5 and target_value(row, target) not in [None, ""]]
    if len(valid) < 2:
        raise ValueError("Need at least two labeled spectra with valid x/y arrays.")
    xmin = max(float(np.min(row["x"])) for row in valid)
    xmax = min(float(np.max(row["x"])) for row in valid)
    if xmin >= xmax:
        xmin = min(float(np.min(row["x"])) for row in valid)
        xmax = max(float(np.max(row["x"])) for row in valid)
    grid = np.linspace(xmin, xmax, int(n_grid))
    X, y, names = [], [], []
    for row in valid:
        order = np.argsort(row["x"])
        x = np.asarray(row["x"])[order]
        yi = np.interp(grid, x, np.asarray(row["y"])[order])
        if norm == "minmax":
            yi = minmax(yi)
        elif norm == "area":
            yi = yi / (abs(integrate(np.abs(yi), grid)) or 1.0)
        elif norm == "zscore":
            yi = (yi - float(np.mean(yi))) / (float(np.std(yi)) or 1.0)
        feats, local_names = [], []
        if "raw" in kinds:
            feats.extend(yi.tolist())
            local_names.extend([f"raw_{i:03d}" for i in range(len(grid))])
        if "derivative" in kinds:
            dy = np.gradient(yi, grid)
            feats.extend(dy.tolist())
            local_names.extend([f"d1_{i:03d}" for i in range(len(grid))])
        if "cdf" in kinds:
            cdf = np.cumsum(np.maximum(yi, 0))
            cdf = cdf / (float(cdf[-1]) or 1.0)
            feats.extend(cdf.tolist())
            local_names.extend([f"cdf_{i:03d}" for i in range(len(grid))])
        if "peak_window" in kinds:
            dy = np.gradient(yi, grid)
            pk = int(np.argmax(yi))
            vals = [float(grid[pk]), float(yi[pk]), integrate(yi, grid), float(np.max(dy)), float(np.min(dy))]
            vals.extend([integrate(yi[idx], grid[idx]) if len(idx) > 1 else 0.0 for idx in np.array_split(np.arange(len(grid)), 4)])
            feats.extend(vals)
            local_names.extend(["peak_x", "peak_y", "area", "derivative_max", "derivative_min", "window_1_area", "window_2_area", "window_3_area", "window_4_area"])
        if not names:
            names = local_names
        X.append(feats)
        y.append(target_value(row, target))
    return np.asarray(X, dtype=float), np.asarray(y, dtype=object), names, grid


def model_pipeline(task: str, name: str, use_pca: bool, n_comp: int):
    if task == "classification":
        models = {"Dummy baseline": DummyClassifier(strategy="most_frequent"), "Logistic regression": LogisticRegression(max_iter=2000, class_weight="balanced"), "Random forest": RandomForestClassifier(n_estimators=300, random_state=7, class_weight="balanced"), "SVM": SVC(kernel="rbf", C=10.0, gamma="scale", class_weight="balanced")}
    else:
        models = {"Dummy baseline": DummyRegressor(strategy="mean"), "Ridge": Ridge(alpha=1.0), "Random forest": RandomForestRegressor(n_estimators=300, random_state=7), "SVR": SVR(kernel="rbf", C=10.0, gamma="scale")}
    steps = [("scale", StandardScaler())]
    if use_pca:
        steps.append(("pca", PCA(n_components=max(1, int(n_comp)), random_state=7)))
    steps.append(("model", models[name]))
    return Pipeline(steps)


def cv_splitter(task: str, y: np.ndarray):
    if len(y) < 4:
        return None
    if task == "classification":
        labels, counts = np.unique(y.astype(str), return_counts=True)
        if len(labels) >= 2 and int(np.min(counts)) >= 2:
            return StratifiedKFold(n_splits=min(5, int(np.min(counts)), len(y)), shuffle=True, random_state=7)
    return KFold(n_splits=min(5, len(y)), shuffle=True, random_state=7)


def train_manual(X, y, task, model_name, use_pca, n_comp):
    if task == "classification":
        ym = y.astype(str)
        labels, counts = np.unique(ym, return_counts=True)
        if len(labels) < 2:
            model_name = "Dummy baseline"
        model = model_pipeline(task, model_name, use_pca, n_comp)
        if len(ym) < 4:
            model.fit(X, ym)
            pred = model.predict(X)
            return {"metrics": {"train_balanced_accuracy": float(balanced_accuracy_score(ym, pred)), "note": "train-only; fewer than four spectra"}, "table": [{"true": str(t), "predicted": str(p)} for t, p in zip(ym, pred)], "model": model, "y_model": ym}
        strat = ym if len(labels) >= 2 and np.min(counts) >= 2 else None
        Xtr, Xte, ytr, yte = train_test_split(X, ym, test_size=0.25, random_state=7, stratify=strat)
        model.fit(Xtr, ytr)
        ptr, pte = model.predict(Xtr), model.predict(Xte)
        return {"metrics": {"train_balanced_accuracy": float(balanced_accuracy_score(ytr, ptr)), "test_balanced_accuracy": float(balanced_accuracy_score(yte, pte)), "test_macro_f1": float(f1_score(yte, pte, average="macro"))}, "table": [{"true": str(t), "predicted": str(p)} for t, p in zip(yte, pte)], "model": model, "y_model": ym}
    if not all(is_number(v) for v in y):
        raise ValueError("Regression target must be numeric.")
    ym = np.asarray([float(v) for v in y], dtype=float)
    model = model_pipeline(task, model_name, use_pca, n_comp)
    if len(ym) < 4:
        model.fit(X, ym)
        pred = model.predict(X)
        return {"metrics": {"train_RMSE": float(np.sqrt(mean_squared_error(ym, pred))), "train_MAE": float(mean_absolute_error(ym, pred)), "note": "train-only; fewer than four spectra"}, "table": [{"true": float(t), "predicted": float(p)} for t, p in zip(ym, pred)], "model": model, "y_model": ym}
    Xtr, Xte, ytr, yte = train_test_split(X, ym, test_size=0.25, random_state=7)
    model.fit(Xtr, ytr)
    ptr, pte = model.predict(Xtr), model.predict(Xte)
    return {"metrics": {"train_RMSE": float(np.sqrt(mean_squared_error(ytr, ptr))), "test_RMSE": float(np.sqrt(mean_squared_error(yte, pte))), "test_MAE": float(mean_absolute_error(yte, pte)), "test_R2": float(r2_score(yte, pte)) if len(yte) > 1 else float("nan")}, "table": [{"true": float(t), "predicted": float(p)} for t, p in zip(yte, pte)], "model": model, "y_model": ym}


def show_learning_curve(model, X: np.ndarray, y_model: np.ndarray, task: str):
    st.subheader("Training curve")
    cv = cv_splitter(task, y_model)
    if cv is None or X.shape[0] < 4:
        st.info("Training curve needs at least four spectra. Showing train-only result above.")
        return
    scoring = "balanced_accuracy" if task == "classification" else "neg_root_mean_squared_error"
    try:
        sizes, train_scores, val_scores = learning_curve(model, X, y_model, cv=cv, scoring=scoring, train_sizes=np.linspace(0.4, 1.0, 5), error_score=np.nan)
        train_mean = np.nanmean(train_scores, axis=1)
        val_mean = np.nanmean(val_scores, axis=1)
        if task == "regression":
            train_mean = -train_mean
            val_mean = -val_mean
            ylabel = "RMSE (lower is better)"
        else:
            ylabel = "Balanced accuracy (higher is better)"
        curve_rows = [{"training_size": int(n), "train": float(t), "validation": float(v)} for n, t, v in zip(sizes, train_mean, val_mean) if math.isfinite(float(t)) and math.isfinite(float(v))]
        if not curve_rows:
            st.warning("Training curve could not be computed with finite scores for this small dataset.")
            return
        if pd is not None:
            st.caption(ylabel)
            st.line_chart(pd.DataFrame(curve_rows), x="training_size", y=["train", "validation"], use_container_width=True)
            st.dataframe(pd.DataFrame(curve_rows), use_container_width=True)
        else:
            st.table(curve_rows)
    except Exception as exc:
        st.warning(f"Training curve skipped: {exc}")


def auto_advisor(rows, target, task, n_grid, max_rows):
    feature_sets = [["peak_window"], ["raw", "peak_window"], ["derivative", "peak_window"], ["cdf", "peak_window"], ["raw"], ["raw", "derivative"], ["raw", "cdf"]]
    models = ["Dummy baseline", "Logistic regression", "SVM", "Random forest"] if task == "classification" else ["Dummy baseline", "Ridge", "SVR", "Random forest"]
    results, failures = [], []
    for fs in feature_sets:
        for norm in ["minmax", "area", "zscore"]:
            try:
                X, y, _, _ = feature_matrix(rows, target, fs, norm, n_grid)
            except Exception as exc:
                failures.append(f"{'+'.join(fs)} / {norm}: {exc}")
                continue
            for model_name in models:
                for n_comp in [None] + [n for n in [2, 4, 8, 16] if n < min(X.shape)]:
                    try:
                        if task == "classification":
                            ym = y.astype(str)
                            if len(np.unique(ym)) < 2 and model_name != "Dummy baseline":
                                continue
                            scoring = "balanced_accuracy"
                        else:
                            if not all(is_number(v) for v in y):
                                raise ValueError("Regression target must be numeric.")
                            ym = np.asarray([float(v) for v in y], dtype=float)
                            scoring = "neg_root_mean_squared_error"
                        cv = cv_splitter(task, ym)
                        model = model_pipeline(task, model_name, n_comp is not None, n_comp or 0)
                        if cv is None:
                            model.fit(X, ym)
                            pred = model.predict(X)
                            if task == "classification":
                                valid = float(balanced_accuracy_score(ym, pred)); train = valid; rank = valid; metric = "validation_balanced_accuracy"
                            else:
                                valid = float(np.sqrt(mean_squared_error(ym, pred))); train = valid; rank = -valid; metric = "validation_RMSE"
                            evaluation = "train-only (<4 samples)"
                        else:
                            scores = cross_validate(model, X, ym, cv=cv, scoring=scoring, return_train_score=True, error_score=np.nan)
                            tr = float(np.nanmean(scores["train_score"])); va = float(np.nanmean(scores["test_score"]))
                            if not math.isfinite(tr) or not math.isfinite(va):
                                raise ValueError("non-finite CV score")
                            if task == "classification":
                                valid = va; train = tr; rank = va; metric = "validation_balanced_accuracy"
                            else:
                                valid = -va; train = -tr; rank = va; metric = "validation_RMSE"
                            evaluation = "cross-validation"
                        gap = train - valid if task == "classification" else valid - train
                        results.append({"feature_set": "+".join(fs), "normalization": norm, "dimension_reduction": "none" if n_comp is None else f"PCA({n_comp})", "model": model_name, metric: valid, "train_score_same_metric": train, "overfit_gap": gap, "rank_score": rank, "evaluation": evaluation, "n_samples": int(X.shape[0]), "n_features": int(X.shape[1])})
                    except Exception as exc:
                        failures.append(f"{'+'.join(fs)} / {norm} / {model_name} / {n_comp}: {exc}")
    results = sorted(results, key=lambda r: (r["rank_score"], -abs(r.get("overfit_gap", 0.0))), reverse=True)
    for i, row in enumerate(results, 1):
        row["rank"] = i
    return results[:max_rows], failures


uploaded = st.file_uploader("Upload ISAAC record JSON files or a ZIP folder of ISAAC records", type=["json", "zip"], accept_multiple_files=True)
if not uploaded:
    st.info("Upload one or more ISAAC JSON records, or a ZIP containing JSON records.")
    st.stop()
try:
    records = read_records(uploaded)
    rows = rows_from_records(records)
except Exception as exc:
    st.error(f"Failed to load records: {exc}")
    st.stop()

st.success(f"Loaded {len(records)} JSON record(s) and detected {len(rows)} spectral/record row(s).")
plottable = [r for r in rows if r.get("x") is not None and r.get("y") is not None and r.get("n_points", 0) > 0]
xas_rows = [r for r in plottable if r.get("is_xas")]
non_xas = [r for r in rows if not r.get("is_xas")]
missing_units = [r for r in plottable if not safe_str(r.get("x_unit")).strip() or not safe_str(r.get("y_unit")).strip()]
groups = sorted({r.get("edge_group", "Unknown absorber/edge") for r in xas_rows})

c1, c2, c3, c4, c5 = st.columns(5)
c1.metric("JSON records", len(records))
c2.metric("Rows", len(rows))
c3.metric("XAS-like", len(xas_rows))
c4.metric("Absorber/edge groups", len(groups))
c5.metric("Missing x/y unit", len(missing_units))
if missing_units:
    st.warning("Some plottable series are missing x or y units.")
else:
    st.success("All plottable series have both x and y units.")

summary_rows = summary_table(rows)
with st.expander("Series classification table", expanded=True):
    if pd is not None:
        st.dataframe(pd.DataFrame(summary_rows), use_container_width=True)
    else:
        st.table(summary_rows)
    st.download_button("Download classification CSV", data=rows_to_csv(summary_rows), file_name="isaac_series_classification.csv", mime="text/csv")
if non_xas:
    with st.expander("Non-XAS or questionable records", expanded=True):
        st.write("These rows are excluded by default from XAS ML because their axes/channels are not incident-energy XAS spectra.")
        if pd is not None:
            st.dataframe(pd.DataFrame(summary_table(non_xas)), use_container_width=True)
        else:
            st.table(summary_table(non_xas))

st.divider()
st.header("Plot spectra by absorber and edge")
plot_scope = st.radio("Records to plot", ["XAS-like only", "All plottable series", "Non-XAS only"], horizontal=True)
if plot_scope == "XAS-like only":
    plot_rows = xas_rows
elif plot_scope == "Non-XAS only":
    plot_rows = [r for r in non_xas if r.get("x") is not None and r.get("y") is not None]
else:
    plot_rows = plottable
plot_groups = sorted({r.get("edge_group", "Unknown absorber/edge") for r in plot_rows})
sel_groups = st.multiselect("Absorber/edge groups", plot_groups, default=([g for g in plot_groups if g != "Unknown absorber/edge"] or plot_groups)[:4])
plot_mode = st.selectbox("Display mode", ["raw", "min-max normalized", "min-max normalized with vertical offset"], index=1)
if pd is None:
    st.warning("pandas is not available, so plotting is disabled.")
else:
    for group in sel_groups:
        group_rows = [r for r in plot_rows if r.get("edge_group") == group]
        with st.expander(f"{group} ({len(group_rows)} series)", expanded=len(sel_groups) <= 2):
            plot_records = []
            for offset, row in enumerate(group_rows[:20]):
                x = np.asarray(row["x"], dtype=float)
                y = np.asarray(row["y"], dtype=float)
                if plot_mode.startswith("min-max"):
                    y = minmax(y)
                if plot_mode.endswith("vertical offset"):
                    y = y + offset * 1.15
                label = " | ".join(v for v in [safe_str(row.get("record_id")) or safe_str(row.get("source_name")), safe_str(row.get("formula")), safe_str(row.get("series_id"))] if v)
                plot_records.extend([{"x": float(a), "y": float(b), "label": label} for a, b in zip(x, y)])
            if plot_records:
                st.line_chart(pd.DataFrame(plot_records), x="x", y="y", color="label", use_container_width=True)

st.divider()
st.header("Train ML model")
train_scope = st.radio("Training records", ["XAS-like only", "All plottable series"], horizontal=True)
train_rows = xas_rows if train_scope == "XAS-like only" else plottable
train_groups = sorted({r.get("edge_group", "Unknown absorber/edge") for r in train_rows})
sel_train_groups = st.multiselect("Absorber/edge groups for training", train_groups, default=[g for g in train_groups if g != "Unknown absorber/edge"] or train_groups)
train_rows = [r for r in train_rows if r.get("edge_group") in sel_train_groups]
if len(train_rows) < 2:
    st.info("Need at least two plottable labeled spectra for ML setup.")
    st.stop()

label_candidates = label_fields(train_rows)
if not label_candidates:
    st.warning("No scalar label fields found in these ISAAC records.")
    st.stop()
target = st.selectbox("Target / label field", label_candidates, index=label_candidates.index("sample.material.formula") if "sample.material.formula" in label_candidates else 0)
label_vals = [v for v in [target_value(r, target) for r in train_rows] if v not in [None, ""]]
reg_ok = bool(label_vals) and all(is_number(v) for v in label_vals)
task = st.radio("Task type", ["classification", "regression"], index=1 if reg_ok and target.startswith("descriptors.") else 0, horizontal=True)
if not SKLEARN_AVAILABLE:
    st.warning(f"scikit-learn is not available, so training is disabled. Import error: {SKLEARN_IMPORT_ERROR}")

st.subheader("Auto-advisor")
st.write("Run a deterministic comparison of feature sets, normalization choices, PCA/no-PCA, and simple models. The recommendation is based on validation performance and overfitting gap.")
a1, a2 = st.columns(2)
advisor_grid = a1.slider("Auto-advisor common-grid points", 32, 512, 128, step=32)
advisor_rows = a2.slider("Configurations to show", 5, 40, 15, step=5)
if st.button("Run Auto-advisor comparison", disabled=not SKLEARN_AVAILABLE, type="secondary"):
    try:
        res, failures = auto_advisor(train_rows, target, task, advisor_grid, advisor_rows)
        if res:
            st.success("Auto-advisor finished. Use the recommendation as a starting point, then verify with grouped validation.")
            best = res[0]
            st.markdown(f"**Recommendation:** `{best['feature_set']}` features, `{best['normalization']}` normalization, `{best['dimension_reduction']}`, `{best['model']}`.")
            if pd is not None:
                df = pd.DataFrame(res)
                st.dataframe(df.drop(columns=["rank_score"], errors="ignore"), use_container_width=True)
                st.download_button("Download Auto-advisor CSV", data=df.to_csv(index=False), file_name="xas_ml_auto_advisor_results.csv", mime="text/csv")
            else:
                st.table(res)
        else:
            st.warning("Auto-advisor could not rank any configuration. Check labels, record count, and task type.")
        if failures:
            with st.expander("Skipped/failed configurations", expanded=False):
                st.write(failures[:80])
    except Exception as exc:
        st.error(f"Auto-advisor failed: {exc}")

st.subheader("Manual model run")
feature_kinds = st.multiselect("Input features", ["raw", "derivative", "cdf", "peak_window"], default=["raw", "peak_window"])
norm = st.selectbox("Spectrum normalization", ["minmax", "area", "zscore", "none"], index=0)
n_grid = st.slider("Common-grid points", 32, 1024, 256, step=32)
model_options = ["Dummy baseline", "Logistic regression", "Random forest", "SVM"] if task == "classification" else ["Dummy baseline", "Ridge", "Random forest", "SVR"]
model_name = st.selectbox("Model", model_options, index=1 if len(model_options) > 1 else 0)
use_pca = st.checkbox("Use PCA before model", value=False)
if use_pca:
    n_comp = st.slider("PCA components", 1, min(32, max(1, len(train_rows) - 1)), min(4, max(1, len(train_rows) - 1)))
else:
    n_comp = 2

if st.button("Train model", type="primary", disabled=not SKLEARN_AVAILABLE):
    try:
        X, y, feature_names, grid = feature_matrix(train_rows, target, feature_kinds, norm, n_grid)
        result = train_manual(X, y, task, model_name, use_pca, n_comp)
        st.success(f"Trained {model_name} on {X.shape[0]} spectra with {X.shape[1]} features.")
        metric_items = list(result["metrics"].items())
        cols = st.columns(max(1, len(metric_items)))
        for col, (key, value) in zip(cols, metric_items):
            if isinstance(value, float) and math.isfinite(value):
                col.metric(key, f"{value:.4g}")
            else:
                col.metric(key, str(value))
        st.subheader("Held-out predictions")
        if pd is not None:
            st.dataframe(pd.DataFrame(result["table"]), use_container_width=True)
        else:
            st.table(result["table"])
        show_learning_curve(result["model"], X, result["y_model"], task)
    except Exception as exc:
        st.error(f"Training failed: {exc}")
