# web_app/pages/2_Machine_learning_for_XAS.py

from __future__ import annotations

import csv
import io
import json
import math
import re
import sys
import zipfile
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import streamlit as st

try:
    import pandas as pd
except Exception:
    pd = None

try:
    from sklearn.decomposition import PCA
    from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
    from sklearn.linear_model import LogisticRegression, Ridge
    from sklearn.metrics import balanced_accuracy_score, f1_score, mean_absolute_error, mean_squared_error, r2_score
    from sklearn.model_selection import KFold, StratifiedKFold, cross_validate, train_test_split
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.svm import SVC, SVR
    SKLEARN_AVAILABLE = True
    SKLEARN_IMPORT_ERROR = None
except Exception as exc:
    SKLEARN_AVAILABLE = False
    SKLEARN_IMPORT_ERROR = exc

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

ML_PAGE_UPDATE_TAG = "v37_2026-07-01_canonical_absorber_edge_labels"
ISAAC_PORTAL_URL = "https://isaac.slac.stanford.edu/portal/"

ENERGY_AXIS_NAMES = ("energy", "incident_energy", "photon_energy", "mono_energy", "e0")
ENERGY_UNITS = ("ev", "electronvolt", "electron_volt", "kev")
ABSORPTION_CHANNEL_NAMES = ("absorption", "absorbance", "mu", "xanes", "xas", "tey", "tfy", "pfy", "herfd", "intensity", "fluorescence", "delta_absorption")
NON_SPECTRAL_Y_NAMES = ("oxidation_state", "coordination_number", "charge", "descriptor")
EDGE_ENERGY_WINDOWS = [
    ("Ni", "L", 830.0, 890.0), ("Cu", "L", 920.0, 970.0), ("C", "K", 260.0, 330.0),
    ("O", "K", 500.0, 560.0), ("Ni", "K", 8200.0, 8500.0), ("Cu", "K", 8850.0, 9100.0),
    ("Ir", "L3", 11100.0, 11350.0), ("Bi", "L3", 13300.0, 13580.0),
    ("Pt", "L3", 11400.0, 11650.0), ("Au", "L3", 11800.0, 12080.0),
]

st.set_page_config(page_title="CO2RR XAS Agent | Machine learning for XAS", layout="wide")
st.title("Agentic machine learning for XAS")
st.caption(f"Update tag: `{ML_PAGE_UPDATE_TAG}`")
st.markdown(f"""
**Goal.** Build an agent-assisted workflow that turns ISAAC-format XAS records into validated spectral datasets, model inputs, trained ML models, performance diagnostics, and suggested next actions for CO2RR catalyst interpretation.

**Data source.** Upload ISAAC record JSON files from the [ISAAC portal]({ISAAC_PORTAL_URL}) or ISAAC-compatible records generated by this XAS agent. The app validates the actual spectral axes/channels before using a record for XAS ML.
""".strip())


def _safe_str(value: Any) -> str:
    return "" if value is None else str(value)


def _lower(value: Any) -> str:
    return _safe_str(value).strip().lower()


def _is_number(value: Any) -> bool:
    try:
        return math.isfinite(float(value))
    except Exception:
        return False


def _as_float_array(values: Any) -> Optional[np.ndarray]:
    if not isinstance(values, list) or not values:
        return None
    try:
        arr = np.asarray(values, dtype=float)
    except Exception:
        return None
    return arr if arr.ndim == 1 and arr.size and np.all(np.isfinite(arr)) else None


def _get_path(data: Dict[str, Any], dotted_path: str) -> Any:
    node: Any = data
    for part in dotted_path.split("."):
        if isinstance(node, dict) and part in node:
            node = node[part]
        else:
            return None
    return node


def _flatten_scalar_paths(data: Any, prefix: str = "", max_depth: int = 5) -> Dict[str, Any]:
    if max_depth < 0:
        return {}
    out: Dict[str, Any] = {}
    if isinstance(data, dict):
        for key, value in data.items():
            if str(key).startswith("_"):
                continue
            child = f"{prefix}.{key}" if prefix else str(key)
            out.update(_flatten_scalar_paths(value, child, max_depth - 1))
    elif isinstance(data, list):
        if len(data) <= 8 and all(not isinstance(v, (dict, list)) for v in data):
            out[prefix] = ", ".join(_safe_str(v) for v in data)
    elif isinstance(data, (str, int, float, bool)) or data is None:
        out[prefix] = data
    return out


def _descriptor_values(record: Dict[str, Any]) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for output in (record.get("descriptors") or {}).get("outputs") or []:
        label = output.get("label") or "descriptor_output"
        for desc in output.get("descriptors") or []:
            name = desc.get("name")
            if name:
                out[f"descriptors.{name}"] = desc.get("value")
                out[f"descriptors.{label}.{name}"] = desc.get("value")
    return out


def _find_first_key(data: Any, key_names: Sequence[str], max_depth: int = 6) -> Any:
    key_set = {_lower(k) for k in key_names}
    if max_depth < 0:
        return None
    if isinstance(data, dict):
        for key, value in data.items():
            if _lower(key) in key_set and not isinstance(value, (dict, list)):
                return value
        for value in data.values():
            found = _find_first_key(value, key_names, max_depth - 1)
            if found not in [None, ""]:
                return found
    elif isinstance(data, list) and len(data) <= 20:
        for value in data:
            found = _find_first_key(value, key_names, max_depth - 1)
            if found not in [None, ""]:
                return found
    return None


def _material_formula(record: Dict[str, Any]) -> str:
    return _safe_str(_get_path(record, "sample.material.formula")) or _safe_str(_get_path(record, "sample.material.name"))


def _canonicalize_absorber(raw_absorber: Any) -> str:
    text = _safe_str(raw_absorber).strip()
    if not text:
        return ""
    cleaned = re.sub(r"[^A-Za-z]", " ", text)
    tokens = [tok for tok in cleaned.split() if tok]
    if not tokens:
        return text
    token = tokens[0]
    return token.upper() if len(token) == 1 else token[0].upper() + token[1:].lower()


def _parse_absorber_from_edge_string(raw_edge: Any) -> str:
    match = re.match(r"^\s*([A-Za-z]{1,2})[\s_\-]", _safe_str(raw_edge).strip())
    return _canonicalize_absorber(match.group(1)) if match else ""


def _canonicalize_edge(raw_edge: Any) -> str:
    text = _safe_str(raw_edge).strip()
    if not text:
        return ""
    upper = text.upper()
    normalized = re.sub(r"[^A-Z0-9]+", " ", upper).replace(" EDGE", " ").replace("EDGE ", " ").strip()
    for pattern, prefix in [(r"\bL\s*([1-3])\b", "L"), (r"\bM\s*([1-5])\b", "M"), (r"\bN\s*([1-7])\b", "N"), (r"\bO\s*([1-7])\b", "O")]:
        match = re.search(pattern, normalized)
        if match:
            return f"{prefix}{match.group(1)}"
    for token in ["K", "L", "M", "N", "O"]:
        if re.search(rf"\b{token}\b", normalized):
            return token
    match = re.search(r"(L[1-3]|M[1-5]|N[1-7]|O[1-7]|K|L|M|N|O)", upper)
    return match.group(1) if match else text.strip().upper()


def _infer_absorber_edge_from_energy(x: Optional[np.ndarray]) -> Tuple[str, str, str]:
    if x is None or not x.size:
        return "unknown", "unknown", "not inferred"
    xmin, xmax = float(np.nanmin(x)), float(np.nanmax(x))
    xmid = 0.5 * (xmin + xmax)
    for absorber, edge, lo, hi in EDGE_ENERGY_WINDOWS:
        if (lo <= xmid <= hi) or (xmin <= lo <= xmax) or (xmin <= hi <= xmax):
            return absorber, edge, "inferred from energy range"
    return "unknown", "unknown", "not inferred"


def _resolve_absorber_edge(record: Dict[str, Any], x: Optional[np.ndarray]) -> Tuple[str, str, str]:
    raw_absorber = (_get_path(record, "system.absorber") or _get_path(record, "system.configuration.absorber") or _get_path(record, "measurement.absorber") or _find_first_key(record, ["absorber", "absorbing_element", "absorber_element", "element"]))
    raw_edge = (_get_path(record, "system.edge") or _get_path(record, "system.configuration.edge") or _get_path(record, "measurement.edge") or _find_first_key(record, ["edge", "absorption_edge"]))
    absorber = _canonicalize_absorber(raw_absorber) or _parse_absorber_from_edge_string(raw_edge)
    edge = _canonicalize_edge(raw_edge)
    if absorber and edge:
        return absorber, edge, "metadata"
    inferred_abs, inferred_edge, source = _infer_absorber_edge_from_energy(x)
    return absorber or inferred_abs or "unknown", edge or inferred_edge or "unknown", source


def _edge_group(absorber: str, edge: str) -> str:
    absorber_c = _canonicalize_absorber(absorber)
    edge_c = _canonicalize_edge(edge)
    if not absorber_c or absorber_c.lower() == "unknown" or not edge_c or edge_c == "UNKNOWN":
        return "Unknown absorber/edge"
    return f"{absorber_c} {edge_c}-edge"


def _record_display_name(row: Dict[str, Any]) -> str:
    record = row.get("record") or {}
    parts = [_safe_str(record.get("record_id")) or _safe_str(row.get("source_name")), _material_formula(record), row.get("edge_group"), _safe_str(row.get("technique")), _safe_str(row.get("series_id"))]
    return " | ".join(part for part in parts if part)


def _read_uploaded_json_records(uploaded_files: Sequence[Any]) -> List[Tuple[str, Dict[str, Any]]]:
    records: List[Tuple[str, Dict[str, Any]]] = []
    for uploaded in uploaded_files or []:
        name = getattr(uploaded, "name", "uploaded")
        payload = uploaded.getvalue()
        if name.lower().endswith(".zip"):
            with zipfile.ZipFile(io.BytesIO(payload)) as zf:
                for member in sorted(zf.namelist()):
                    if member.endswith("/") or not member.lower().endswith(".json"):
                        continue
                    try:
                        data = json.loads(zf.read(member).decode("utf-8"))
                    except Exception:
                        continue
                    if isinstance(data, dict):
                        records.append((member, data))
        elif name.lower().endswith(".json"):
            data = json.loads(payload.decode("utf-8"))
            if isinstance(data, dict):
                records.append((name, data))
    return records


def _choose_primary_channel(channels: Sequence[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    if not channels:
        return None
    for channel in channels:
        if _lower(channel.get("role")) == "primary_signal":
            return channel
    for channel in channels:
        if any(token in _lower(channel.get("name")) for token in ABSORPTION_CHANNEL_NAMES):
            return channel
    return channels[0]


def _classify_series(record: Dict[str, Any], x_name: str, x_unit: str, y_name: str, y_unit: str) -> Tuple[bool, str, str]:
    x_name_l, x_unit_l, y_name_l = _lower(x_name), _lower(x_unit), _lower(y_name)
    technique = _lower(_get_path(record, "system.technique")) or _lower(_get_path(record, "system.configuration.technique"))
    if x_name_l in {"q", "qz"} or "angstrom^-1" in x_unit_l or "1/angstrom" in x_unit_l:
        return False, "not_xas_reflectivity_or_scattering", "x-axis is q/scattering vector, not incident energy"
    if "time" in x_name_l or x_unit_l in {"s", "sec", "second", "min", "minute", "h", "hour"}:
        return False, "not_xas_time_series", "x-axis is time, not incident energy"
    if any(token in y_name_l for token in NON_SPECTRAL_Y_NAMES):
        return False, "not_xas_descriptor_series", "y-axis is a descriptor/time trace rather than spectral intensity"
    has_energy_x = any(token in x_name_l for token in ENERGY_AXIS_NAMES) or x_name_l in {"e", "energy_ev"}
    has_energy_unit = any(unit == x_unit_l or unit in x_unit_l for unit in ENERGY_UNITS)
    has_xas_y = any(token in y_name_l for token in ABSORPTION_CHANNEL_NAMES)
    if has_energy_x and has_energy_unit and has_xas_y:
        if "delta" in y_name_l or "difference" in y_name_l:
            return True, "xas_derived_difference_spectrum", "energy-axis differential XAS spectrum"
        if "herfd" in technique:
            return True, "herfd_xas_like", "energy-axis HERFD-XAS/HERFD-XANES-like spectrum"
        if "xanes" in technique:
            return True, "xanes_like", "energy-axis XANES-like spectrum"
        return True, "xas_like", "energy-axis XAS/XANES-like spectrum"
    if has_energy_x and has_energy_unit:
        return True, "xas_like_uncertain_y", "energy-axis spectrum, but y channel name is not a standard XAS signal"
    return False, "not_xas_unknown_axis", "does not have an incident-energy x-axis with eV/keV units"


def _build_series_rows(records: Sequence[Tuple[str, Dict[str, Any]]]) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for source_name, record in records:
        series_list = (record.get("measurement") or {}).get("series") or []
        if not series_list:
            absorber, edge, edge_source = _resolve_absorber_edge(record, None)
            metadata = {**_flatten_scalar_paths(record), **_descriptor_values(record)}
            rows.append({"source_name": source_name, "record_id": record.get("record_id"), "series_id": "", "has_series": False, "is_xas": False, "classification": "not_plottable_no_measurement_series", "reason": "no measurement.series found", "x_name": "", "x_unit": "", "y_name": "", "y_unit": "", "n_points": 0, "absorber": absorber, "edge": edge, "edge_source": edge_source, "edge_group": _edge_group(absorber, edge), "technique": _get_path(record, "system.technique") or _get_path(record, "system.configuration.technique"), "formula": _material_formula(record), "record": record, "metadata": metadata, "x": None, "y": None})
            continue
        for idx, series in enumerate(series_list):
            x_obj = (series.get("independent_variables") or [{}])[0]
            y_obj = _choose_primary_channel(series.get("channels") or []) or {}
            x, y = _as_float_array(x_obj.get("values")), _as_float_array(y_obj.get("values"))
            x_name, x_unit, y_name, y_unit = _safe_str(x_obj.get("name")), _safe_str(x_obj.get("unit")), _safe_str(y_obj.get("name")), _safe_str(y_obj.get("unit"))
            series_id = _safe_str(series.get("series_id")) or f"series_{idx}"
            absorber, edge, edge_source = _resolve_absorber_edge(record, x)
            edge_group = _edge_group(absorber, edge)
            metadata = {**_flatten_scalar_paths(record), **_descriptor_values(record), "series.series_id": series_id, "series.x_name": x_name, "series.x_unit": x_unit, "series.y_name": y_name, "series.y_unit": y_unit, "derived.n_points": int(x.size if x is not None else 0), "derived.absorber": absorber, "derived.edge": edge, "derived.edge_group": edge_group}
            if x is None or y is None or x.size != y.size:
                is_xas, classification, reason = False, "not_plottable_invalid_xy", "missing/non-numeric x or y values, or length mismatch"
            else:
                is_xas, classification, reason = _classify_series(record, x_name, x_unit, y_name, y_unit)
            rows.append({"source_name": source_name, "record_id": record.get("record_id"), "series_id": series_id, "has_series": True, "is_xas": is_xas, "classification": classification, "reason": reason, "x_name": x_name, "x_unit": x_unit, "y_name": y_name, "y_unit": y_unit, "n_points": int(x.size if x is not None else 0), "absorber": absorber, "edge": edge, "edge_source": edge_source, "edge_group": edge_group, "technique": _get_path(record, "system.technique") or _get_path(record, "system.configuration.technique"), "formula": _material_formula(record), "record": record, "metadata": metadata, "x": x, "y": y})
    return rows


def _summary_table(rows: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    keys = ["source_name", "record_id", "series_id", "technique", "formula", "absorber", "edge", "edge_group", "edge_source", "x_name", "x_unit", "y_name", "y_unit", "n_points", "is_xas", "classification", "reason"]
    return [{key.replace("_name", ""): row.get(key) for key in keys} for row in rows]


def _rows_to_csv(rows: Sequence[Dict[str, Any]]) -> str:
    if not rows:
        return ""
    out = io.StringIO()
    writer = csv.DictWriter(out, fieldnames=list(rows[0].keys()))
    writer.writeheader(); writer.writerows(rows)
    return out.getvalue()


def _minmax(y: np.ndarray) -> np.ndarray:
    span = float(np.max(y) - np.min(y))
    return np.zeros_like(y) if span == 0 else (y - float(np.min(y))) / span


def _area_norm(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    area = float(np.trapz(np.abs(y), x))
    return y.astype(float) if area == 0 else y / area


def _target_value(row: Dict[str, Any], path: str) -> Any:
    if path.startswith(("descriptors.", "series.", "derived.")):
        return (row.get("metadata") or {}).get(path)
    value = _get_path(row.get("record") or {}, path)
    return value if value is not None else (row.get("metadata") or {}).get(path)


def _candidate_label_fields(rows: Sequence[Dict[str, Any]]) -> List[str]:
    preferred = ["sample.material.formula", "sample.material.name", "derived.absorber", "derived.edge", "derived.edge_group", "sample.ml_labels.adsorbate_identity", "sample.ml_labels.adsorption_motif", "sample.ml_labels.oxidation_coordination_class", "system.technique", "source_type", "record_domain"]
    keys = set()
    for row in rows:
        for key, value in (row.get("metadata") or {}).items():
            if value is not None and not (isinstance(value, str) and len(value) > 160):
                keys.add(key)
    return [key for key in preferred if key in keys] + sorted(keys - set(preferred))


def _common_grid(rows: Sequence[Dict[str, Any]], n_grid: int) -> np.ndarray:
    xmin = max(float(np.min(row["x"])) for row in rows if row.get("x") is not None)
    xmax = min(float(np.max(row["x"])) for row in rows if row.get("x") is not None)
    if xmin >= xmax:
        xmin = min(float(np.min(row["x"])) for row in rows if row.get("x") is not None)
        xmax = max(float(np.max(row["x"])) for row in rows if row.get("x") is not None)
    return np.linspace(xmin, xmax, int(n_grid))


def _build_feature_matrix(rows: Sequence[Dict[str, Any]], target_path: str, feature_kinds: Sequence[str], normalization: str, n_grid: int) -> Tuple[np.ndarray, np.ndarray, List[str], np.ndarray]:
    valid = [row for row in rows if row.get("x") is not None and row.get("y") is not None and row.get("n_points", 0) >= 5 and _target_value(row, target_path) not in [None, ""]]
    if len(valid) < 2:
        raise ValueError("Need at least two labeled spectra with valid x/y arrays.")
    grid = _common_grid(valid, n_grid)
    X, targets, feature_names = [], [], []
    for row in valid:
        order = np.argsort(row["x"])
        x, y = np.asarray(row["x"])[order], np.asarray(row["y"])[order]
        yi = np.interp(grid, x, y)
        if normalization == "minmax": yi = _minmax(yi)
        elif normalization == "area": yi = _area_norm(grid, yi)
        elif normalization == "zscore": yi = (yi - float(np.mean(yi))) / (float(np.std(yi)) or 1.0)
        feats, names = [], []
        if "raw" in feature_kinds:
            feats += yi.tolist(); names += [f"raw_{i:03d}" for i in range(len(grid))]
        if "derivative" in feature_kinds:
            dy = np.gradient(yi, grid); feats += dy.tolist(); names += [f"d1_{i:03d}" for i in range(len(grid))]
        if "cdf" in feature_kinds:
            cdf = np.cumsum(np.maximum(yi, 0)); cdf = cdf / (float(cdf[-1]) or 1.0); feats += cdf.tolist(); names += [f"cdf_{i:03d}" for i in range(len(grid))]
        if "peak_window" in feature_kinds:
            dy = np.gradient(yi, grid); peak_idx = int(np.argmax(yi)); vals = [float(grid[peak_idx]), float(yi[peak_idx]), float(np.trapz(yi, grid)), float(np.max(dy)), float(np.min(dy))]
            for idx in np.array_split(np.arange(len(grid)), 4): vals.append(float(np.trapz(yi[idx], grid[idx])) if len(idx) > 1 else 0.0)
            feats += vals; names += ["peak_x", "peak_y", "area", "derivative_max", "derivative_min", "window_1_area", "window_2_area", "window_3_area", "window_4_area"]
        if not feature_names: feature_names = names
        X.append(feats); targets.append(_target_value(row, target_path))
    return np.asarray(X, dtype=float), np.asarray(targets, dtype=object), feature_names, grid


def _make_model(task: str, model_name: str, use_pca: bool, n_components: int):
    if task == "classification":
        model = {"Logistic regression": LogisticRegression(max_iter=2000, class_weight="balanced"), "Random forest": RandomForestClassifier(n_estimators=300, random_state=7, class_weight="balanced"), "SVM": SVC(kernel="rbf", C=10.0, gamma="scale", class_weight="balanced")}[model_name]
    else:
        model = {"Ridge": Ridge(alpha=1.0), "Random forest": RandomForestRegressor(n_estimators=300, random_state=7), "SVR": SVR(kernel="rbf", C=10.0, gamma="scale")}[model_name]
    steps = [("scale", StandardScaler())]
    if use_pca: steps.append(("pca", PCA(n_components=max(1, int(n_components)), random_state=7)))
    steps.append(("model", model))
    return Pipeline(steps)


def _make_cv(task: str, y: np.ndarray):
    if task == "classification":
        labels, counts = np.unique(y.astype(str), return_counts=True)
        if len(labels) < 2 or int(np.min(counts)) < 2: raise ValueError("Auto-advisor needs at least two examples in each class.")
        return StratifiedKFold(n_splits=min(5, int(np.min(counts)), len(y)), shuffle=True, random_state=7)
    return KFold(n_splits=min(5, len(y)), shuffle=True, random_state=7)


def _run_auto_advisor(rows: Sequence[Dict[str, Any]], target_path: str, task: str, n_grid: int, max_configs: int) -> Tuple[List[Dict[str, Any]], List[str]]:
    feature_sets = [["peak_window"], ["derivative", "peak_window"], ["cdf", "peak_window"], ["raw"], ["raw", "peak_window"], ["raw", "derivative"], ["raw", "cdf"]]
    normalizations = ["minmax", "area", "zscore"]
    models = ["Logistic regression", "SVM", "Random forest"] if task == "classification" else ["Ridge", "SVR", "Random forest"]
    results, failures = [], []
    for feature_set in feature_sets:
        for norm in normalizations:
            try:
                X, y, _, _ = _build_feature_matrix(rows, target_path, feature_set, norm, n_grid)
                if task == "regression" and not all(_is_number(v) for v in y): raise ValueError("Regression target must be numeric.")
                y_model = y.astype(str) if task == "classification" else np.asarray([float(v) for v in y], dtype=float)
                cv = _make_cv(task, y)
            except Exception as exc:
                failures.append(f"{'+'.join(feature_set)} / {norm}: {exc}"); continue
            pca_options: List[Optional[int]] = [None] + [n for n in [2, 4, 8, 16] if n < min(X.shape)]
            for model_name in models:
                for n_comp in pca_options:
                    try:
                        model = _make_model(task, model_name, n_comp is not None, n_comp or 0)
                        scoring = "balanced_accuracy" if task == "classification" else "neg_root_mean_squared_error"
                        cvres = cross_validate(model, X, y_model, cv=cv, scoring=scoring, return_train_score=True, error_score=np.nan)
                        train_raw, valid_raw = float(np.nanmean(cvres["train_score"])), float(np.nanmean(cvres["test_score"]))
                        if task == "regression":
                            train_disp, valid_disp, score_name, gap, rank_score = -train_raw, -valid_raw, "validation_RMSE", -valid_raw - (-train_raw), valid_raw
                        else:
                            train_disp, valid_disp, score_name, gap, rank_score = train_raw, valid_raw, "validation_balanced_accuracy", train_raw - valid_raw, valid_raw
                        pca_label = "none" if n_comp is None else f"PCA({n_comp})"
                        advice = []
                        advice.append("uses dimension reduction" if n_comp is not None else "no dimension reduction")
                        if gap > 0.20: advice.append("possible overfitting")
                        if "peak_window" in feature_set and "raw" not in feature_set: advice.append("compact/interpretable features")
                        if "derivative" in feature_set: advice.append("edge-shift sensitive")
                        if "cdf" in feature_set: advice.append("smooth/integral line-shape")
                        results.append({"feature_set": "+".join(feature_set), "normalization": norm, "dimension_reduction": pca_label, "model": model_name, score_name: valid_disp, "train_score_same_metric": train_disp, "overfit_gap": gap, "rank_score": rank_score, "n_samples": int(X.shape[0]), "n_features": int(X.shape[1]), "advice": "; ".join(advice)})
                    except Exception as exc:
                        failures.append(f"{'+'.join(feature_set)} / {norm} / {model_name} / {n_comp}: {exc}")
    results = sorted(results, key=lambda item: (item["rank_score"], -abs(item.get("overfit_gap", 0.0))), reverse=True)
    for i, item in enumerate(results, 1): item["rank"] = i
    return results[:max_configs], failures


def _advisor_recommendation(results: Sequence[Dict[str, Any]], task: str) -> List[str]:
    if not results: return ["No valid configuration finished. Check labels, class balance, and record count."]
    best = results[0]; recs = [f"Recommended setting: **{best['feature_set']}** features, **{best['normalization']}** normalization, **{best['dimension_reduction']}**, **{best['model']}**."]
    recs.append("Use PCA/dimension reduction." if best["dimension_reduction"] != "none" else "Do not use PCA for now; the sweep did not require it for the top setting.")
    if "peak_window" in best["feature_set"]: recs.append("Keep peak/window features as an interpretable baseline.")
    if "derivative" in best["feature_set"]: recs.append("Derivative features are useful, so edge position/white-line shifts likely matter.")
    if "cdf" in best["feature_set"]: recs.append("CDF features are useful, so integrated line shape may be robust.")
    if best.get("overfit_gap", 0) > 0.20: recs.append("The train-validation gap is still large; add records or reduce feature dimension before trusting predictions.")
    recs.append("Use the top few rows as candidates; prefer a slightly lower score if it has fewer features and a smaller overfit gap.")
    return recs


def _train_manual(X: np.ndarray, y: np.ndarray, task: str, model_name: str, use_pca: bool, n_components: int) -> Dict[str, Any]:
    if len(y) < 4: raise ValueError("Need at least four labeled spectra for a train/test split.")
    model = _make_model(task, model_name, use_pca, n_components)
    if task == "classification":
        labels, counts = np.unique(y.astype(str), return_counts=True)
        strat = y.astype(str) if np.min(counts) >= 2 else None
        Xtr, Xte, ytr, yte = train_test_split(X, y.astype(str), test_size=0.25, random_state=7, stratify=strat)
        model.fit(Xtr, ytr); ptr, pte = model.predict(Xtr), model.predict(Xte)
        return {"metrics": {"train_balanced_accuracy": float(balanced_accuracy_score(ytr, ptr)), "test_balanced_accuracy": float(balanced_accuracy_score(yte, pte)), "test_macro_f1": float(f1_score(yte, pte, average="macro"))}, "prediction_table": [{"true": str(t), "predicted": str(p)} for t, p in zip(yte, pte)]}
    ynum = np.asarray([float(v) for v in y], dtype=float)
    Xtr, Xte, ytr, yte = train_test_split(X, ynum, test_size=0.25, random_state=7)
    model.fit(Xtr, ytr); ptr, pte = model.predict(Xtr), model.predict(Xte)
    return {"metrics": {"train_RMSE": float(mean_squared_error(ytr, ptr, squared=False)), "test_RMSE": float(mean_squared_error(yte, pte, squared=False)), "test_MAE": float(mean_absolute_error(yte, pte)), "test_R2": float(r2_score(yte, pte)) if len(yte) > 1 else float("nan")}, "prediction_table": [{"true": float(t), "predicted": float(p)} for t, p in zip(yte, pte)]}


uploaded_files = st.file_uploader("Upload ISAAC record JSON files or a ZIP folder of ISAAC records", type=["json", "zip"], accept_multiple_files=True)
if not uploaded_files:
    st.info("Upload one or more ISAAC JSON records, or a ZIP containing JSON records."); st.stop()

try:
    records = _read_uploaded_json_records(uploaded_files); rows = _build_series_rows(records)
except Exception as exc:
    st.exception(exc); st.stop()

summary_rows = _summary_table(rows)
plottable_rows = [r for r in rows if r.get("x") is not None and r.get("y") is not None and r.get("n_points", 0) > 0]
xas_rows = [r for r in plottable_rows if r.get("is_xas")]
non_xas_rows = [r for r in rows if not r.get("is_xas")]
unit_missing_rows = [r for r in plottable_rows if not _safe_str(r.get("x_unit")).strip() or not _safe_str(r.get("y_unit")).strip()]
edge_groups = sorted({r.get("edge_group", "Unknown absorber/edge") for r in xas_rows})

m1, m2, m3, m4, m5 = st.columns(5)
m1.metric("JSON records", len(records)); m2.metric("Series", len(rows)); m3.metric("XAS-like", len(xas_rows)); m4.metric("Absorber/edge groups", len(edge_groups)); m5.metric("Missing x/y unit", len(unit_missing_rows))
st.success("All plottable series have both x and y units.") if not unit_missing_rows else st.warning("Some plottable series are missing x or y units.")

with st.expander("Series classification table", expanded=True):
    if pd is not None: st.dataframe(pd.DataFrame(summary_rows), use_container_width=True)
    else: st.dataframe(summary_rows, use_container_width=True)
    st.download_button("Download classification CSV", data=_rows_to_csv(summary_rows), file_name="isaac_series_classification.csv", mime="text/csv")

if non_xas_rows:
    with st.expander("Non-XAS or questionable records", expanded=True):
        st.write("These are excluded by default from XAS ML because their actual axes/channels are not incident-energy XAS spectra.")
        st.dataframe(pd.DataFrame(_summary_table(non_xas_rows)) if pd is not None else _summary_table(non_xas_rows), use_container_width=True)

st.divider(); st.header("Plot spectra by absorber and edge")
plot_scope = st.radio("Records to plot", ["XAS-like only", "All plottable series", "Non-XAS only"], horizontal=True)
candidate_plot_rows = xas_rows if plot_scope == "XAS-like only" else ([r for r in non_xas_rows if r.get("x") is not None and r.get("y") is not None] if plot_scope == "Non-XAS only" else plottable_rows)
plot_groups = sorted({r.get("edge_group", "Unknown absorber/edge") for r in candidate_plot_rows})
selected_plot_groups = st.multiselect("Absorber/edge groups", plot_groups, default=([g for g in plot_groups if g != "Unknown absorber/edge"] or plot_groups)[:4])
plot_mode = st.selectbox("Display mode", ["raw", "min-max normalized", "min-max normalized with vertical offset"], index=1)
max_points = int(st.slider("Maximum points per series for display", 50, 2000, 800, step=50))

if pd is None:
    st.warning("pandas is not available, so plotting is disabled.")
else:
    for group in selected_plot_groups:
        group_rows = [r for r in candidate_plot_rows if r.get("edge_group", "Unknown absorber/edge") == group]
        labels = [_record_display_name(r) for r in group_rows]
        with st.expander(f"{group} ({len(group_rows)} series)", expanded=len(selected_plot_groups) <= 2):
            chosen = set(st.multiselect(f"Series for {group}", labels, default=labels[:min(len(labels), 12)], key=f"plot_select_{group}"))
            selected_rows = [r for r, label in zip(group_rows, labels) if label in chosen]
            plot_records = []
            for offset, row in enumerate(selected_rows):
                x, y = np.asarray(row["x"], dtype=float), np.asarray(row["y"], dtype=float)
                if plot_mode.startswith("min-max"): y = _minmax(y)
                if plot_mode.endswith("vertical offset"): y = y + offset * 1.15
                if len(x) > max_points:
                    idx = np.linspace(0, len(x) - 1, max_points).astype(int); x, y = x[idx], y[idx]
                label = _record_display_name(row)
                plot_records += [{"x": float(xi), "y": float(yi), "label": label} for xi, yi in zip(x, y)]
            if plot_records:
                st.caption(f"x: {selected_rows[0].get('x_name')} ({selected_rows[0].get('x_unit')})    y: {selected_rows[0].get('y_name')} ({selected_rows[0].get('y_unit')}); display mode: {plot_mode}")
                st.line_chart(pd.DataFrame(plot_records), x="x", y="y", color="label", use_container_width=True)

st.divider(); st.header("Train ML model")
st.caption("For quick screening and workflow development. For publication-quality benchmarking, use grouped validation and an external held-out test set.")
training_scope = st.radio("Training records", ["XAS-like only", "All plottable series"], horizontal=True)
training_rows = xas_rows if training_scope == "XAS-like only" else plottable_rows
training_groups = sorted({r.get("edge_group", "Unknown absorber/edge") for r in training_rows})
selected_training_groups = st.multiselect("Absorber/edge groups for training", training_groups, default=[g for g in training_groups if g != "Unknown absorber/edge"] or training_groups)
training_rows = [r for r in training_rows if r.get("edge_group", "Unknown absorber/edge") in selected_training_groups]
if len(training_rows) < 2: st.info("Need at least two plottable labeled spectra for ML setup."); st.stop()

label_candidates = _candidate_label_fields(training_rows)
if not label_candidates: st.warning("No scalar label fields found in these ISAAC records."); st.stop()
target_path = st.selectbox("Target / label field", label_candidates, index=label_candidates.index("sample.material.formula") if "sample.material.formula" in label_candidates else 0)
label_values = [v for v in [_target_value(r, target_path) for r in training_rows] if v not in [None, ""]]
can_be_regression = label_values and all(_is_number(v) for v in label_values)
task = st.radio("Task type", ["classification", "regression"], index=1 if can_be_regression and target_path.startswith("descriptors.") else 0, horizontal=True)
if not SKLEARN_AVAILABLE: st.warning(f"scikit-learn is not available, so training is disabled. Import error: {SKLEARN_IMPORT_ERROR}")

st.subheader("Auto-advisor")
st.write("Run a deterministic comparison of feature sets, normalization choices, PCA/no-PCA, and simple models. The recommendation is based on validation performance and overfitting gap, not on an LLM guess.")
c1, c2 = st.columns(2)
with c1: advisor_grid = st.slider("Auto-advisor common-grid points", 32, 512, 128, step=32)
with c2: advisor_max_rows = st.slider("Configurations to show", 5, 40, 15, step=5)
if st.button("Run Auto-advisor comparison", disabled=not SKLEARN_AVAILABLE, type="secondary"):
    try:
        advisor_results, advisor_failures = _run_auto_advisor(training_rows, target_path, task, advisor_grid, advisor_max_rows)
        if not advisor_results:
            st.warning("No advisor configuration completed successfully.")
        else:
            st.success("Auto-advisor finished. Use the recommendation as a starting point, then verify with grouped validation.")
            st.markdown("**Recommendation**")
            for rec in _advisor_recommendation(advisor_results, task): st.write(f"- {rec}")
            if pd is not None:
                df = pd.DataFrame(advisor_results)
                show_cols = [c for c in ["rank", "feature_set", "normalization", "dimension_reduction", "model", "validation_balanced_accuracy", "validation_RMSE", "train_score_same_metric", "overfit_gap", "n_samples", "n_features", "advice"] if c in df.columns]
                st.dataframe(df[show_cols], use_container_width=True)
                st.download_button("Download Auto-advisor CSV", data=df.to_csv(index=False), file_name="xas_ml_auto_advisor_results.csv", mime="text/csv")
            if advisor_failures:
                with st.expander("Skipped/failed configurations", expanded=False): st.write(advisor_failures[:50])
    except Exception as exc: st.exception(exc)

st.subheader("Manual model run")
feature_kinds = st.multiselect("Input features", ["raw", "derivative", "cdf", "peak_window"], default=["raw", "peak_window"])
normalization = st.selectbox("Spectrum normalization", ["minmax", "area", "zscore", "none"], index=0)
n_grid = st.slider("Common-grid points", 32, 1024, 256, step=32)
model_name = st.selectbox("Model", ["Logistic regression", "Random forest", "SVM"] if task == "classification" else ["Ridge", "Random forest", "SVR"], index=0)
use_pca = st.checkbox("Use PCA before model", value=False)
n_components = st.slider("PCA components", 1, min(32, max(1, len(training_rows) - 1)), min(4, max(1, len(training_rows) - 1))) if use_pca else 2
if st.button("Train model", type="primary", disabled=not SKLEARN_AVAILABLE):
    try:
        X, y, feature_names, grid = _build_feature_matrix(training_rows, target_path, feature_kinds, normalization, n_grid)
        if task == "regression" and not all(_is_number(v) for v in y): raise ValueError("Regression target must be numeric.")
        result = _train_manual(X, y, task, model_name, use_pca, n_components)
        st.success(f"Trained {model_name} on {X.shape[0]} spectra with {X.shape[1]} features.")
        cols = st.columns(max(1, len(result["metrics"])))
        for col, (key, value) in zip(cols, result["metrics"].items()): col.metric(key, f"{value:.4g}" if isinstance(value, float) and math.isfinite(value) else str(value))
        st.subheader("Held-out predictions")
        st.dataframe(pd.DataFrame(result["prediction_table"]) if pd is not None else result["prediction_table"], use_container_width=True)
    except Exception as exc: st.exception(exc)
