"""Tests for NERSC submit/monitor workflow helpers."""

import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from workflow.nersc_workflow import (
    NERSCJob,
    NERSCJobManager,
    discover_submit_scripts,
    execute_nersc_full_workflow,
    parse_completed_jobs,
)


class FakeSLURMRunner:
    def __init__(self):
        self.commands = []
        self.next_job_id = 1000

    def __call__(self, cmd, **kwargs):
        self.commands.append(list(cmd))
        exe = Path(cmd[0]).name
        if exe == "sbatch":
            self.next_job_id += 1
            return subprocess.CompletedProcess(cmd, 0, stdout=f"{self.next_job_id}\n", stderr="")
        if exe == "squeue":
            # Empty squeue means the job has left the active queue; manager then checks sacct.
            return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")
        if exe == "sacct":
            return subprocess.CompletedProcess(cmd, 0, stdout="COMPLETED\n", stderr="")
        return subprocess.CompletedProcess(cmd, 1, stdout="", stderr="unexpected command")


def test_discover_submit_scripts_from_generated_inputs_shape():
    inputs = {
        "relax": {"submit_script": "/tmp/run/relax/submit_relax.sh"},
        "xas": {
            "Cu_K_edge": {
                "FEFF": {"submit": "/tmp/run/xas/Cu_K_edge/FEFF/submit.sh"},
                "FDMNES": {"submit": "/tmp/run/xas/Cu_K_edge/FDMNES/submit.sh"},
                "VASP": {"submit": "/tmp/run/xas/Cu_K_edge/VASP/submit.sh"},
            }
        },
    }
    feff_scripts = discover_submit_scripts(inputs, software_filter="FEFF")
    assert len(feff_scripts) == 1
    assert feff_scripts[0]["software"] == "FEFF"
    assert feff_scripts[0]["absorber"] == "Cu"
    assert feff_scripts[0]["edge"] == "K"

    all_scripts = discover_submit_scripts(inputs, software_filter="all")
    assert len(all_scripts) == 4




def test_feff_generator_writes_lightshow_style_sections():
    from tools.utils import read_poscar
    from tools.xas_input_generator import FEFFInputGenerator

    structure_file = REPO_ROOT / "example_ouput" / "VASP" / "XAS" / "POSCAR"
    structure = read_poscar(str(structure_file))

    with tempfile.TemporaryDirectory() as tmp:
        feff_dir = Path(tmp) / "FEFF"
        feff_file = FEFFInputGenerator().write_input(
            structure=structure,
            output_dir=str(feff_dir),
            absorber="Cu",
            edge="K",
            radius=4.0,
        )
        generated = {name: (feff_dir / name).read_text() for name in ["HEADER", "PARAMETERS", "POTENTIALS", "ATOMS", "feff.inp"]}

    assert Path(feff_file).name == "feff.inp"
    assert generated["HEADER"].startswith("* This FEFF.inp file generated by CO2RR-XAS Agent")
    assert generated["PARAMETERS"].startswith("CONTROL 1 1 1 1 1 1")
    assert "EDGE K" in generated["PARAMETERS"]
    assert generated["POTENTIALS"].startswith("POTENTIALS")
    assert "      0" in generated["POTENTIALS"]
    assert generated["ATOMS"].startswith("ATOMS")
    assert generated["ATOMS"].endswith("END\n")
    assert generated["feff.inp"].endswith("END\n")
    for section in ["HEADER", "PARAMETERS", "POTENTIALS", "ATOMS"]:
        assert generated[section].strip() in generated["feff.inp"]


def test_nersc_workflow_can_submit_and_monitor_with_fake_slurm():
    runner = FakeSLURMRunner()
    manager = NERSCJobManager(runner=runner)
    structure_file = REPO_ROOT / "example_ouput" / "VASP" / "XAS" / "POSCAR"

    with tempfile.TemporaryDirectory() as tmp:
        result = execute_nersc_full_workflow(
            structure_file=str(structure_file),
            output_dir=str(Path(tmp) / "nersc"),
            software="FEFF",
            submit=True,
            monitor=True,
            parse_when_complete=False,
            poll_interval=1,
            job_manager=manager,
            nersc_account="m1234",
            nersc_queue="regular",
            nersc_nodes=1,
            nersc_walltime="00:30:00",
            edge_override="K",
        )

    assert result["status"] == "success"
    assert len(result["submitted_jobs"]) == 1
    assert result["submitted_jobs"][0]["software"] == "FEFF"
    assert result["submitted_jobs"][0]["state"] == "COMPLETED"
    assert any(Path(cmd[0]).name == "sbatch" for cmd in runner.commands)
    assert any(Path(cmd[0]).name == "squeue" for cmd in runner.commands)
    assert any(Path(cmd[0]).name == "sacct" for cmd in runner.commands)


def test_agent_exposes_nersc_dry_run_workflow():
    from agent.co2rr_xas_agent import create_agent

    structure_file = REPO_ROOT / "example_ouput" / "VASP" / "XAS" / "POSCAR"
    with tempfile.TemporaryDirectory() as tmp:
        agent = create_agent(use_llm=False)
        result = agent.run_nersc_workflow(
            structure_file=str(structure_file),
            output_dir=str(Path(tmp) / "agent_dry_run"),
            software="FEFF",
            submit=False,
            nersc_account="m1234",
            nersc_nodes=1,
            edge_override="K",
        )

    assert result["status"] == "success"
    assert result["submitted_jobs"]
    assert result["submitted_jobs"][0]["state"] == "DRY_RUN"
    assert result["job_manager"]["backend"] in {"custodian", "sequential"}


def test_generated_nersc_workflow_carries_ml_metadata_in_dry_run():
    from agent.co2rr_xas_agent import process_request

    request = (
        'Run NERSC workflow dry run for catalyst: elements: [Cu, Au] composition: CuAu '
        'surface_facet: "111" site_type: interface structure_id: "CuAu_111_OCCO_bridge_001" '
        'adsorbate: identity: "OCCO" formula: "C2O2" intermediate_class: "C2" '
        'binding_mode: "bridge" adsorption_site: "Cu-Au interface" binding_atom: "C" K edge'
    )

    with tempfile.TemporaryDirectory() as tmp:
        result = process_request(request, output_dir=tmp, use_llm=False)
        metadata_path = next(Path(tmp).rglob("structure_info.json"))
        import json
        metadata = json.loads(metadata_path.read_text())

    assert result["status"] == "success"
    assert result["submitted_jobs"]
    assert metadata["catalyst"]["elements"] == ["Cu", "Au"]
    assert metadata["catalyst"]["composition"] == "CuAu"
    assert metadata["catalyst"]["structure_id"] == "CuAu_111_OCCO_bridge_001"
    assert metadata["adsorbate_metadata"]["identity"] == "OCCO"
    assert metadata["adsorbate_metadata"]["binding_mode"] == "bridge"




def test_custodian_output_validation_skips_strict_truncated_fdmnes_parse():
    import shutil

    structure_file = REPO_ROOT / "example_ouput" / "VASP" / "XAS" / "POSCAR"
    with tempfile.TemporaryDirectory() as tmp:
        output_dir = Path(tmp) / "FDMNES"
        shutil.copytree(REPO_ROOT / "example_ouput" / "FDMNES", output_dir)
        conv = next(output_dir.glob("*_conv.txt"))
        conv.write_text("\n".join(conv.read_text().splitlines()[:25]) + "\n")
        job = NERSCJob(
            job_id="123",
            script=str(output_dir / "submit.sh"),
            output_dir=str(output_dir),
            software="FDMNES",
            absorber="Cu",
            edge="K",
            state="COMPLETED",
        )
        records = parse_completed_jobs(
            [job],
            structure_file=str(structure_file),
            parameters={"strict_output_validation": True},
        )

    assert len(records) == 1
    record = records[0]
    assert record["validation_result"]["backend"] == "custodian"
    assert record["validation_result"]["skip_parse"] is True
    assert record["validation_result"]["output_validation"]["status"] == "error"
    assert record["parse_result"]["status"] == "error"
    assert job.parse_status == "error"




def test_prompt_generates_lateral_cu_au_interface_occo_and_au_l3_only():
    from agent.co2rr_xas_agent import process_request
    from tools.utils import read_poscar
    import json

    request = (
        "Generate XAS inputs for OCCO adsorbate on Cu(111)-Au(111) interface, "
        "K edge, radius 7 Angstrom, energy range -5 0.2 50, "
        "NERSC account m5268, do not submit"
    )

    with tempfile.TemporaryDirectory() as tmp:
        result = process_request(request, output_dir=tmp, use_llm=False)
        root = Path(tmp)
        metadata = json.loads(next(root.rglob("structure_info.json")).read_text())
        structure = read_poscar(str(next(root.rglob("OCCO/structure/POSCAR"))))
        xas_keys = set(result["inputs"]["xas"].keys())
        relax_poscar = next(root.rglob("relax/POSCAR")).read_text()

    assert result["status"] == "success"
    assert metadata["interface"]["type"] == "lateral"
    assert "Au_L3_edge" in xas_keys
    assert "Au_K_edge" not in xas_keys
    assert "Cu_K_edge" in xas_keys
    assert "Selective dynamics" in relax_poscar
    assert "F  F  F" in relax_poscar
    split = metadata["interface"]["split_coordinate"]
    carbon_x = [pos[0] for atom, pos in zip(structure["atoms"], structure["positions"]) if atom == "C"]
    assert len(carbon_x) == 2
    assert min(carbon_x) < split <= max(carbon_x)


def test_agent_returns_needs_input_for_missing_generation_context():
    from agent.co2rr_xas_agent import process_request

    with tempfile.TemporaryDirectory() as tmp:
        result = process_request("Generate XAS inputs", output_dir=tmp, use_llm=False)

    assert result["status"] == "needs_input"
    assert result["missing_information"]
    assert result["missing_information"][0]["field"] == "metals"
    assert "suggestions" in result


def test_agent_recovers_nersc_submit_to_dry_run_when_slurm_missing():
    from agent.co2rr_xas_agent import process_request
    import workflow.nersc_workflow as workflow_module

    original = workflow_module.NERSCJobManager.is_nersc_environment
    workflow_module.NERSCJobManager.is_nersc_environment = staticmethod(lambda: False)
    try:
        with tempfile.TemporaryDirectory() as tmp:
            result = process_request(
                "Run on NERSC for OCCO adsorbate on Cu(111), K edge, submit and monitor",
                output_dir=tmp,
                use_llm=False,
            )
    finally:
        workflow_module.NERSCJobManager.is_nersc_environment = original

    assert result["status"] == "success"
    assert result["submitted_jobs"]
    assert all(job["state"] == "DRY_RUN" for job in result["submitted_jobs"])
    assert "agent" in result
    assert result["agent"]["warnings"]
    assert result["agent"]["recovery_actions"]


if __name__ == "__main__":
    test_discover_submit_scripts_from_generated_inputs_shape()
    test_nersc_workflow_can_submit_and_monitor_with_fake_slurm()
    test_agent_exposes_nersc_dry_run_workflow()
    test_generated_nersc_workflow_carries_ml_metadata_in_dry_run()
    test_custodian_output_validation_skips_strict_truncated_fdmnes_parse()
    test_prompt_generates_lateral_cu_au_interface_occo_and_au_l3_only()
    test_agent_returns_needs_input_for_missing_generation_context()
    test_agent_recovers_nersc_submit_to_dry_run_when_slurm_missing()
    print("NERSC workflow tests passed")
