"""
FDMNES Input Generator - Generate FDMNES input files for XAS calculations
Integrates with skill-based parameter system
"""

from typing import Dict, Any, Optional, List, Union
from pathlib import Path
import numpy as np

from pymatgen.core import Structure, Element
from pymatgen.io.ase import AseAtomsAdaptor

try:
    from ase import Atoms
    ASE_AVAILABLE = True
except ImportError:
    ASE_AVAILABLE = False

from generators.base_generator import BaseGenerator


# FDMNES edge notation mapping
EDGE_NOTATION = {
    'K': 'K',
    'L1': 'L1',
    'L2': 'L2',
    'L3': 'L3',
    'M1': 'M1',
    'M2': 'M2',
    'M3': 'M3',
    'M4': 'M4',
    'M5': 'M5',
}

# Core hole lifetime broadening (eV) for common edges
GAMMA_HOLE_DEFAULTS = {
    'K': {'Cu': 1.55, 'Fe': 1.19, 'Co': 1.33, 'Ni': 1.44, 'Zn': 1.67, 'Au': 5.31, 'Pt': 5.10, 'Ag': 2.66, 'Pd': 2.42},
    'L3': {'Cu': 0.57, 'Fe': 0.40, 'Co': 0.46, 'Ni': 0.52, 'Au': 5.54, 'Pt': 5.24, 'Ag': 2.30, 'Pd': 2.06},
    'L2': {'Cu': 0.73, 'Fe': 0.53, 'Co': 0.60, 'Ni': 0.67, 'Au': 5.54, 'Pt': 5.24, 'Ag': 2.30, 'Pd': 2.06},
}


class FDMNESXASGenerator(BaseGenerator):
    """Generate FDMNES input files for XAS calculations."""
    
    def __init__(self):
        super().__init__(skill_id='fdmnes_xas_calculation')
    
    def generate(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate FDMNES input file for XAS calculation.
        
        Args:
            params: Validated parameters
        
        Returns:
            Dictionary with fdmnes input content
        """
        # Get structure
        structure = self._get_structure(params['structure'])
        
        absorbing_atom = params['absorbing_atom']
        edge = params['edge']
        
        # Build context for conditional defaults
        context = {
            'edge': edge,
            'calculation_type': params.get('calculation_type', 'xanes')
        }
        
        # Re-merge with context to get edge-specific and calculation-type defaults
        full_params = self.registry.merge_with_defaults(
            self.skill_id, params, context=context
        )
        
        # Determine absorbing atom index
        absorbing_index = self._get_absorbing_index(structure, absorbing_atom)
        absorbing_element = str(structure[absorbing_index].specie)
        
        # Build FDMNES input content
        fdmnes_inp = self._build_fdmnes_input(
            structure=structure,
            params=full_params,
            absorbing_index=absorbing_index,
            absorbing_element=absorbing_element,
            edge=edge
        )
        
        return {
            'fdmnes_inp': fdmnes_inp,
            'structure': structure,
            'absorbing_index': absorbing_index,
            'absorbing_element': absorbing_element,
            'params': full_params
        }
    
    def _get_structure(self, structure_input: Any) -> Structure:
        """Convert various structure inputs to pymatgen Structure."""
        if isinstance(structure_input, Structure):
            return structure_input
        elif isinstance(structure_input, str):
            return Structure.from_file(structure_input)
        elif isinstance(structure_input, dict):
            if 'lattice' in structure_input:
                return Structure.from_dict(structure_input)
            else:
                raise ValueError("Invalid structure dictionary format")
        elif ASE_AVAILABLE and isinstance(structure_input, Atoms):
            adaptor = AseAtomsAdaptor()
            return adaptor.get_structure(structure_input)
        else:
            raise ValueError(f"Cannot convert {type(structure_input)} to Structure")
    
    def _get_absorbing_index(
        self, 
        structure: Structure, 
        absorbing_atom: Dict[str, Any]
    ) -> int:
        """Determine the absorbing atom index."""
        if 'index' in absorbing_atom:
            return absorbing_atom['index']
        
        element = absorbing_atom.get('element')
        if element:
            for i, site in enumerate(structure):
                if str(site.specie) == element:
                    return i
            raise ValueError(f"No {element} atom found in structure")
        
        raise ValueError("Must specify either 'index' or 'element' for absorbing_atom")
    
    def _build_fdmnes_input(
        self,
        structure: Structure,
        params: Dict[str, Any],
        absorbing_index: int,
        absorbing_element: str,
        edge: str
    ) -> str:
        """Build the FDMNES input file content."""
        lines = []
        
        # Header
        lines.append("! FDMNES input file generated by CO2RR_XAS_agent")
        lines.append("! " + "="*60)
        lines.append("")
        
        # Filout - output file prefix
        lines.append("Filout")
        lines.append(f"  {absorbing_element}_{edge}_xas")
        lines.append("")
        
        # Range - energy range
        range_params = params.get('range', {})
        emin = range_params.get('emin', -10.0)
        emax = range_params.get('emax', 50.0)
        estep = range_params.get('estep', 0.5)
        lines.append("Range")
        lines.append(f"  {emin:.1f} {estep:.2f} {emax:.1f}")
        lines.append("")
        
        # Radius
        radius = params.get('radius', 6.0)
        lines.append("Radius")
        lines.append(f"  {radius:.2f}")
        lines.append("")
        
        # Edge
        lines.append("Edge")
        lines.append(f"  {EDGE_NOTATION.get(edge, edge)}")
        lines.append("")
        
        # Absorber
        lines.append("Absorber")
        lines.append(f"  1")  # First atom in the cluster is the absorber
        lines.append("")
        
        # SCF
        if params.get('scf', True):
            lines.append("SCF")
            lines.append("")
        
        # Screening
        if params.get('screening', True):
            lines.append("Screening")
            lines.append("")
        
        # Quadrupole
        if params.get('quadrupole', False):
            lines.append("Quadrupole")
            lines.append("")
        
        # Relativistic
        if params.get('relativistic', True):
            lines.append("Relativism")
            lines.append("")
        
        # Spin-orbit
        if params.get('spinorbit', False):
            lines.append("Spinorbit")
            lines.append("")
        
        # Green's function method
        if params.get('green', False):
            lines.append("Green")
            lines.append("")
        
        # Memory save
        if params.get('memory_save', False):
            lines.append("Memory_save")
            lines.append("")
        
        # Density of states
        if params.get('density_of_states', False):
            lines.append("Density")
            lines.append("")
        
        # Polarization
        polarization = params.get('polarization', {})
        if 'linear' in polarization:
            pol = polarization['linear']
            lines.append("Polarize")
            lines.append(f"  {pol[0]:.4f} {pol[1]:.4f} {pol[2]:.4f}")
            lines.append("")
        
        # Magnetism (for XMCD)
        magnetism = params.get('magnetism', {})
        if magnetism.get('enabled', False):
            axis = magnetism.get('axis', [0, 0, 1])
            lines.append("Magnetism")
            lines.append(f"  {axis[0]:.4f} {axis[1]:.4f} {axis[2]:.4f}")
            lines.append("")
        
        # Convolution parameters
        convolution = params.get('convolution', {})
        gamma_hole = convolution.get('gamma_hole')
        
        # Use element-specific gamma_hole if not specified
        if gamma_hole is None:
            edge_gammas = GAMMA_HOLE_DEFAULTS.get(edge, {})
            gamma_hole = edge_gammas.get(absorbing_element, 1.0)
        
        lines.append("Gamma_hole")
        lines.append(f"  {gamma_hole:.3f}")
        lines.append("")
        
        # Arctangent convolution
        if convolution.get('method') == 'arctangent':
            gamma_max = convolution.get('gamma_max', 5.0)
            ecent = convolution.get('ecent', 30.0)
            elarg = convolution.get('elarg', 30.0)
            lines.append("Efermi")
            lines.append(f"  {ecent:.1f}")
            lines.append("")
            lines.append("Gamma_max")
            lines.append(f"  {gamma_max:.2f}")
            lines.append("")
            lines.append("Elarg")
            lines.append(f"  {elarg:.1f}")
            lines.append("")
        
        # Calculation type specific keywords
        calc_type = params.get('calculation_type', 'xanes')
        if calc_type == 'xmcd':
            lines.append("XMCD")
            lines.append("")
        elif calc_type == 'rxd':
            lines.append("RXD")
            lines.append("")
        elif calc_type == 'dafs':
            lines.append("DAFS")
            lines.append("")
        
        # Crystal structure
        lines.append("! Crystal structure")
        lines.append("! " + "-"*60)
        lines.append("")
        
        # Check if periodic or cluster
        if self._is_periodic(structure):
            lines.extend(self._write_crystal_structure(structure, absorbing_index))
        else:
            lines.extend(self._write_cluster_structure(structure, absorbing_index, radius))
        
        # End
        lines.append("")
        lines.append("End")
        
        return '\n'.join(lines)
    
    def _is_periodic(self, structure: Structure) -> bool:
        """Check if structure should be treated as periodic."""
        # Check if it's a molecule (very large vacuum)
        lattice = structure.lattice
        volume_per_atom = lattice.volume / len(structure)
        
        # If volume per atom is very large, likely a molecule/cluster
        return volume_per_atom < 100.0  # Arbitrary threshold
    
    def _write_crystal_structure(
        self, 
        structure: Structure, 
        absorbing_index: int
    ) -> List[str]:
        """Write crystal structure in FDMNES format."""
        lines = []
        
        # Space group (use P1 for safety)
        lines.append("Spgroup")
        lines.append("  P 1")
        lines.append("")
        
        # Crystal parameters
        lattice = structure.lattice
        lines.append("Crystal")
        lines.append(f"  {lattice.a:.6f} {lattice.b:.6f} {lattice.c:.6f} "
                    f"{lattice.alpha:.3f} {lattice.beta:.3f} {lattice.gamma:.3f}")
        lines.append("")
        
        # Atoms
        lines.append("! Z  x  y  z  (fractional coordinates)")
        
        # Put absorbing atom first
        absorbing_site = structure[absorbing_index]
        z = Element(str(absorbing_site.specie)).Z
        frac = absorbing_site.frac_coords
        lines.append(f"  {z}  {frac[0]:.6f}  {frac[1]:.6f}  {frac[2]:.6f}")
        
        # Other atoms
        for i, site in enumerate(structure):
            if i != absorbing_index:
                z = Element(str(site.specie)).Z
                frac = site.frac_coords
                lines.append(f"  {z}  {frac[0]:.6f}  {frac[1]:.6f}  {frac[2]:.6f}")
        
        return lines
    
    def _write_cluster_structure(
        self, 
        structure: Structure, 
        absorbing_index: int,
        radius: float
    ) -> List[str]:
        """Write cluster structure in FDMNES format."""
        lines = []
        
        lines.append("Molecule")
        lines.append("")
        
        # Get absorbing atom position as origin
        absorbing_pos = structure[absorbing_index].coords
        
        # Build atom list with distances
        atom_list = []
        for i, site in enumerate(structure):
            rel_pos = site.coords - absorbing_pos
            distance = np.linalg.norm(rel_pos)
            
            if distance <= radius + 0.1:  # Include atoms within radius
                atom_list.append({
                    'z': Element(str(site.specie)).Z,
                    'x': rel_pos[0],
                    'y': rel_pos[1],
                    'z_coord': rel_pos[2],
                    'distance': distance,
                    'is_absorber': i == absorbing_index
                })
        
        # Sort by distance, absorber first
        atom_list.sort(key=lambda x: (not x['is_absorber'], x['distance']))
        
        lines.append(f"! {len(atom_list)} atoms in cluster")
        lines.append("! Z  x  y  z  (Cartesian coordinates in Angstroms)")
        
        for atom in atom_list:
            lines.append(f"  {atom['z']}  {atom['x']:.6f}  {atom['y']:.6f}  {atom['z_coord']:.6f}")
        
        return lines
    
    def write_files(self, outputs: Dict[str, Any], output_dir: Path) -> None:
        """Write FDMNES input file."""
        output_dir = Path(output_dir)
        
        # Write main input file
        with open(output_dir / 'fdmfile.txt', 'w') as f:
            f.write(outputs['fdmnes_inp'])
        
        # Also write a run script
        run_script = self._generate_run_script(outputs)
        with open(output_dir / 'run_fdmnes.sh', 'w') as f:
            f.write(run_script)
    
    def _generate_run_script(self, outputs: Dict[str, Any]) -> str:
        """Generate a shell script to run FDMNES."""
        params = outputs.get('params', {})
        absorbing_element = outputs.get('absorbing_element', 'X')
        edge = params.get('edge', 'K')
        
        script = f"""#!/bin/bash
# FDMNES run script generated by CO2RR_XAS_agent
# Calculation: {absorbing_element} {edge}-edge

# Set FDMNES executable path (modify as needed)
FDMNES_EXE="${{FDMNES_EXE:-fdmnes}}"

# Check if FDMNES is available
if ! command -v $FDMNES_EXE &> /dev/null; then
    echo "Error: FDMNES executable not found"
    echo "Set FDMNES_EXE environment variable or add fdmnes to PATH"
    exit 1
fi

# Run FDMNES
echo "Starting FDMNES calculation..."
echo "Input file: fdmfile.txt"
echo "Output prefix: {absorbing_element}_{edge}_xas"

$FDMNES_EXE < fdmfile.txt > fdmnes.log 2>&1

# Check if successful
if [ $? -eq 0 ]; then
    echo "FDMNES calculation completed successfully"
    echo "Output files:"
    ls -la {absorbing_element}_{edge}_xas*
else
    echo "FDMNES calculation failed. Check fdmnes.log for details"
    exit 1
fi
"""
        return script