"""
FEFF Input Generator - Generate FEFF input files for XAS calculations using Lightshow
"""

from typing import Dict, Any, Optional, List
from pathlib import Path
import warnings
import numpy as np

from pymatgen.core import Structure

# Import from your Lightshow fork
try:
    from lightshow.parameters.feff import FEFFParameters
    LIGHTSHOW_AVAILABLE = True
except ImportError:
    LIGHTSHOW_AVAILABLE = False
    warnings.warn("Lightshow not available. Using fallback FEFF parameter generation.")

from generators.base_generator import BaseGenerator


# FEFF edge codes
EDGE_CODES = {
    'K': 'K',
    'L1': 'L1',
    'L2': 'L2', 
    'L3': 'L3',
    'M1': 'M1',
    'M2': 'M2',
    'M3': 'M3',
    'M4': 'M4',
    'M5': 'M5',
}


class FEFFXASGenerator(BaseGenerator):
    """Generate FEFF input files for XAS calculations."""
    
    def __init__(self):
        super().__init__(skill_id='feff_xas_calculation')
    
    def generate(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate FEFF input file for XAS calculation.
        
        Args:
            params: Validated parameters
        
        Returns:
            Dictionary with feff.inp content
        """
        structure = params['structure']
        if isinstance(structure, str):
            structure = Structure.from_file(structure)
        elif isinstance(structure, dict):
            structure = Structure.from_dict(structure)
        
        absorbing_atom = params['absorbing_atom']
        edge = params['edge']
        
        # Build context for conditional defaults
        context = {
            'edge': edge,
            'spectroscopy_type': params.get('spectroscopy_type', 'XANES')
        }
        
        # Re-merge with context to get spectroscopy-specific defaults
        full_params = self.registry.merge_with_defaults(
            self.skill_id, params, context=context
        )
        
        if LIGHTSHOW_AVAILABLE:
            outputs = self._generate_with_lightshow(structure, full_params)
        else:
            outputs = self._generate_fallback(structure, full_params)
        
        outputs['params'] = full_params
        return outputs
    
    def _generate_with_lightshow(
        self, 
        structure: Structure, 
        params: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Generate using Lightshow library."""
        absorbing_atom = params['absorbing_atom']
        edge = params['edge']
        
        # Determine absorbing atom index
        if 'index' in absorbing_atom:
            absorbing_index = absorbing_atom['index']
        else:
            element = absorbing_atom['element']
            for i, site in enumerate(structure):
                if str(site.specie) == element:
                    absorbing_index = i
                    break
            else:
                raise ValueError(f"No {element} atom found in structure")
        
        # Create Lightshow FEFF parameters
        radius = params.get('radius', {})
        
        feff_params = FEFFParameters(
            structure=structure,
            absorbing_atom=absorbing_index,
            edge=edge,
            radius=radius.get('fms', 6.0),
            scf_radius=radius.get('scf', 5.0),
        )
        
        # Get generated content
        feff_inp = feff_params.get_feff_input()
        
        return {
            'feff_inp': feff_inp,
            'structure': structure,
            'absorbing_index': absorbing_index,
        }
    
    def _generate_fallback(
        self, 
        structure: Structure, 
        params: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Fallback generation without Lightshow."""
        absorbing_atom = params['absorbing_atom']
        edge = params['edge']
        
        # Determine absorbing atom index
        if 'index' in absorbing_atom:
            absorbing_index = absorbing_atom['index']
        else:
            element = absorbing_atom['element']
            for i, site in enumerate(structure):
                if str(site.specie) == element:
                    absorbing_index = i
                    break
            else:
                raise ValueError(f"No {element} atom found in structure")
        
        # Build feff.inp content
        feff_inp = self._build_feff_input(structure, params, absorbing_index)
        
        return {
            'feff_inp': feff_inp,
            'structure': structure,
            'absorbing_index': absorbing_index,
        }
    
    def _build_feff_input(
        self, 
        structure: Structure, 
        params: Dict[str, Any],
        absorbing_index: int
    ) -> str:
        """Build feff.inp file content."""
        lines = []
        
        # Title
        lines.append("TITLE XAS calculation generated by CO2RR_XAS_agent")
        lines.append("")
        
        # Edge
        edge = params['edge']
        absorbing_element = str(structure[absorbing_index].specie)
        lines.append(f"EDGE {edge}")
        lines.append("")
        
        # S02
        s02 = params.get('s02', 1.0)
        lines.append(f"S02 {s02}")
        lines.append("")
        
        # Core hole
        corehole = params.get('corehole', 'FSR')
        lines.append(f"COREHOLE {corehole}")
        lines.append("")
        
        # Control card
        spectroscopy_type = params.get('spectroscopy_type', 'XANES')
        if spectroscopy_type == 'XANES':
            lines.append("CONTROL 1 1 1 1 1 1")
            lines.append("XANES")
        else:
            lines.append("CONTROL 1 1 1 1 1 1")
            lines.append("EXAFS")
            rpath = params.get('rpath', 10.0)
            lines.append(f"RPATH {rpath}")
        lines.append("")
        
        # SCF
        radius = params.get('radius', {})
        scf_radius = radius.get('scf', 5.0)
        scf_iterations = params.get('scf_iterations', 100)
        lines.append(f"SCF {scf_radius} 0 {scf_iterations} 0.2 3")
        lines.append("")
        
        # FMS
        fms_radius = radius.get('fms', 6.0)
        fms_order = params.get('fms_order', 0)
        lines.append(f"FMS {fms_radius} {fms_order}")
        lines.append("")
        
        # Exchange
        exchange = params.get('exchange', 'hedin-lundqvist')
        exchange_map = {
            'hedin-lundqvist': '0 0 0.0 0.0',
            'dirac-hara': '1 0 0.0 0.0',
            'ground-state': '2 0 0.0 0.0',
            'dhaka': '3 0 0.0 0.0',
        }
        lines.append(f"EXCHANGE {exchange_map.get(exchange, '0 0 0.0 0.0')}")
        lines.append("")
        
        # POTENTIALS
        lines.append("POTENTIALS")
        lines.append("* ipot   Z   element   l_scmt   l_fms   stoichiometry")
        
        # Get unique elements and assign potential indices
        elements = []
        for site in structure:
            el = str(site.specie)
            if el not in elements:
                elements.append(el)
        
        # Absorbing atom gets ipot=0
        absorbing_el = str(structure[absorbing_index].specie)
        
        from pymatgen.core import Element
        
        # ipot 0 is always the absorbing atom
        z = Element(absorbing_el).Z
        lines.append(f"   0   {z}   {absorbing_el}   -1   -1   0.001")
        
        # Other elements
        ipot = 1
        for el in elements:
            z = Element(el).Z
            count = sum(1 for site in structure if str(site.specie) == el)
            if el == absorbing_el:
                # Non-absorbing atoms of same element
                lines.append(f"   {ipot}   {z}   {el}   -1   -1   {count - 1}")
            else:
                lines.append(f"   {ipot}   {z}   {el}   -1   -1   {count}")
            ipot += 1
        
        lines.append("")
        
        # ATOMS
        lines.append("ATOMS")
        lines.append("* x   y   z   ipot   tag   distance")
        
        # Get absorbing atom position as origin
        absorbing_pos = structure[absorbing_index].coords
        
        # Build atom list with distances
        atom_list = []
        for i, site in enumerate(structure):
            rel_pos = site.coords - absorbing_pos
            distance = np.linalg.norm(rel_pos)
            el = str(site.specie)
            
            if i == absorbing_index:
                ipot = 0
            else:
                ipot = elements.index(el) + 1
            
            atom_list.append({
                'x': rel_pos[0],
                'y': rel_pos[1],
                'z': rel_pos[2],
                'ipot': ipot,
                'tag': el,
                'distance': distance,
                'index': i
            })
        
        # Sort by distance
        atom_list.sort(key=lambda x: x['distance'])
        
        # Filter by FMS radius
        max_radius = fms_radius + 2.0  # Include atoms slightly beyond FMS radius
        
        for atom in atom_list:
            if atom['distance'] <= max_radius:
                lines.append(
                    f"   {atom['x']:10.6f}   {atom['y']:10.6f}   {atom['z']:10.6f}   "
                    f"{atom['ipot']}   {atom['tag']}   {atom['distance']:.4f}"
                )
        
        lines.append("")
        lines.append("END")
        
        return '\n'.join(lines)
    
    def write_files(self, outputs: Dict[str, Any], output_dir: Path) -> None:
        """Write FEFF input file."""
        output_dir = Path(output_dir)
        
        with open(output_dir / 'feff.inp', 'w') as f:
            f.write(outputs['feff_inp'])