"""Web-app helpers for the durable NERSC relax-to-XAS workflow.

These functions keep the Streamlit UI out of the workflow engine.  The app calls
one local helper to prepare a package, uploads that package with the existing
SFAPI client, and then starts/refreshes/restarts/cancels the NERSC-side workflow
by running the generated shell entry points in the remote run directory.
"""

from __future__ import annotations

import json
import os
import re
from argparse import Namespace
from pathlib import Path, PurePosixPath
from typing import Any, Dict, Optional

from tools.nersc_workflow_package import create_workflow
from tools.structure_generator import StructureGenerator
from tools.xas_input_generator import NERSCScriptGenerator, RelaxationInputGenerator, VASPXASInputGenerator

DEFAULT_NERSC_POTCAR_DIR = "/global/common/software/nersc9/vasp/dependencies/pseudopotentials/PBE/potpaw_PBE"
DEFAULT_NERSC_ACCOUNT = os.environ.get("CO2RR_NERSC_ACCOUNT", os.environ.get("NERSC_ACCOUNT", "m5268"))
DEFAULT_VASP6_MPI_RANKS_PER_NODE = 64
DEFAULT_VASP6_OMP_NUM_THREADS = 2
DEFAULT_VASP6_CPUS_PER_TASK = 4
DEFAULT_VASP_SRUN_COMMAND = 'srun -n "${SLURM_NTASKS:-64}" -c 4 --cpu-bind=cores vasp_std'


def sanitize_name(name: Any, max_len: int = 80) -> str:
    text = re.sub(r"[^A-Za-z0-9_.+-]+", "_", str(name or "structure")).strip("._-")
    return (text or "structure")[:max_len]


def slurm_safe_job_name(name: Any, max_len: int = 64) -> str:
    return sanitize_name(name, max_len=max_len).replace(".", "_") or "web_xas_job"


def sample_label_from_structure(structure: Dict[str, Any], fallback: str = "web_xas_agent") -> str:
    meta = dict((structure or {}).get("metadata", {}) or {})
    ads = meta.get("adsorbate") or "clean"
    if ads in {None, "", "None"}:
        ads = "clean"
    facet = meta.get("facet") or meta.get("facet1") or "111"
    if meta.get("element"):
        base = f"{meta.get('element')}_{facet}_{ads}"
    elif meta.get("element1") or meta.get("element2"):
        e1 = meta.get("element1", "M1")
        e2 = meta.get("element2", "M2")
        base = f"{e1}_{e2}_{facet}_{ads}"
    else:
        base = fallback
    return slurm_safe_job_name(base)


def unique_elements_in_order(structure: Dict[str, Any]) -> list[str]:
    elems: list[str] = []
    for atom in structure.get("atoms", []) or []:
        if atom not in elems:
            elems.append(atom)
    return elems


def potcar_symbol_for_element(element: str) -> str:
    return VASPXASInputGenerator.DEFAULT_POTCAR_MAP.get(element, element)


def write_make_potcar_script(structure: Dict[str, Any], output_dir: Path, potcar_dir: str) -> Path:
    output_dir = Path(output_dir)
    potcar_dir = (potcar_dir or DEFAULT_NERSC_POTCAR_DIR).strip() or DEFAULT_NERSC_POTCAR_DIR
    lines = [
        "#!/bin/bash",
        "set -euo pipefail",
        "",
        "# Generated by CO2RR XAS Agent full NERSC workflow package.",
        f"POTCAR_DIR=\"${{CO2RR_POTCAR_DIR:-{potcar_dir}}}\"",
        "if [ ! -d \"${POTCAR_DIR}\" ]; then",
        "  echo \"ERROR: POTCAR_DIR does not exist: ${POTCAR_DIR}\" >&2",
        "  exit 1",
        "fi",
        "rm -f POTCAR",
    ]
    for elem in unique_elements_in_order(structure):
        symbol = potcar_symbol_for_element(elem)
        lines.extend([
            f"if [ ! -f \"${{POTCAR_DIR}}/{symbol}/POTCAR\" ]; then",
            f"  echo \"ERROR: Missing POTCAR: ${{POTCAR_DIR}}/{symbol}/POTCAR\" >&2",
            "  exit 1",
            "fi",
            f"cat \"${{POTCAR_DIR}}/{symbol}/POTCAR\" >> POTCAR",
        ])
    lines.append("echo \"Wrote POTCAR using ${POTCAR_DIR}\"")
    path = output_dir / "make_potcar.sh"
    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o755)
    return path


def patch_incar_value(lines: list[str], key: str, value: Any) -> list[str]:
    key_upper = key.upper()
    out: list[str] = []
    replaced = False
    for line in lines:
        stripped = line.strip()
        if stripped.upper().startswith(f"{key_upper} ="):
            out.append(f"{key_upper} = {value}")
            replaced = True
        else:
            out.append(line)
    if not replaced:
        out.append(f"{key_upper} = {value}")
    return out


def patch_vasp_relaxation_incar(incar_path: Path, settings: Dict[str, Any]) -> None:
    if not incar_path.exists():
        return
    lines = incar_path.read_text().splitlines()
    replacements = {
        "ENCUT": int(settings.get("encut", 520)),
        "EDIFF": settings.get("ediff", "1E-6"),
        "IBRION": int(settings.get("ibrion", 2)),
        "NSW": int(settings.get("nsw", 200)),
        "EDIFFG": settings.get("ediffg", "-0.02"),
        "ISIF": int(settings.get("isif", 2)),
        "ISPIN": int(settings.get("ispin", 2)),
        "NCORE": int(settings.get("ncore", 8)),
        "LREAL": settings.get("lreal", "Auto"),
        "ISMEAR": int(settings.get("ismear", 0)),
        "SIGMA": settings.get("sigma", "0.05"),
    }
    lines = [line for line in lines if not any(line.strip().upper().startswith(f"{tag} =") for tag in {"LWAVE", "LCHARG"})]
    for key, value in replacements.items():
        lines = patch_incar_value(lines, key, value)
    incar_path.write_text("\n".join(lines) + "\n")


def patch_vasp_submit_for_nersc_cpu(submit_path: Path) -> None:
    """Make a generated relaxation submit script self-contained for NERSC."""
    if not submit_path.exists():
        return
    text = submit_path.read_text()
    lines = []
    inserted_tasks = False
    for line in text.splitlines():
        stripped = line.strip()
        if re.match(r"^#SBATCH\s+(--ntasks-per-node(?:=|\s)|--ntasks(?:=|\s)|-n\b|--cpus-per-task(?:=|\s))", stripped):
            continue
        lines.append(line)
        if not inserted_tasks and re.match(r"^#SBATCH\s+(-N\b|--nodes(?:=|\s))", stripped):
            lines.append(f"#SBATCH --ntasks-per-node={DEFAULT_VASP6_MPI_RANKS_PER_NODE}")
            lines.append(f"#SBATCH --cpus-per-task={DEFAULT_VASP6_CPUS_PER_TASK}")
            inserted_tasks = True
    if not inserted_tasks:
        insert_at = 0
        for i, line in enumerate(lines):
            if line.strip().startswith("#SBATCH"):
                insert_at = i + 1
        lines[insert_at:insert_at] = [
            f"#SBATCH --ntasks-per-node={DEFAULT_VASP6_MPI_RANKS_PER_NODE}",
            f"#SBATCH --cpus-per-task={DEFAULT_VASP6_CPUS_PER_TASK}",
        ]
    text = "\n".join(lines).rstrip() + "\n"
    if "./make_potcar.sh" not in text:
        potcar_block = (
            "# Build POTCAR before launching VASP.\n"
            "if [ ! -s POTCAR ]; then\n"
            "  echo 'POTCAR not found or empty; running ./make_potcar.sh'\n"
            "  ./make_potcar.sh || EXIT_CODE=$?\n"
            "fi\n\n"
            "if [ \"${EXIT_CODE}\" -eq 0 ]; then\n"
            f"  {DEFAULT_VASP_SRUN_COMMAND} > vasp.out 2>&1 || EXIT_CODE=$?\n"
            "else\n"
            "  echo 'Skipping VASP because POTCAR generation failed with exit code '${EXIT_CODE}\n"
            "fi"
        )
        replaced = False
        for old in [
            "srun vasp_std > vasp.out 2>&1 || EXIT_CODE=$?",
            "srun vasp_std > vasp.out 2>&1",
            "srun vasp_std > vasp.out",
        ]:
            if old in text:
                text = text.replace(old, potcar_block, 1)
                replaced = True
                break
        if not replaced:
            text = text.rstrip() + "\n" + potcar_block + "\n"
    text = re.sub(r"^export\s+OMP_NUM_THREADS=.*$", f"export OMP_NUM_THREADS={DEFAULT_VASP6_OMP_NUM_THREADS}", text, flags=re.M)
    if "export OMP_NUM_THREADS=" not in text:
        text = text.replace("module load", f"export OMP_NUM_THREADS={DEFAULT_VASP6_OMP_NUM_THREADS}\nexport OMP_PLACES=threads\nexport OMP_PROC_BIND=spread\nmodule load", 1)
    text = re.sub(r"srun\b(?:\s+(?:-[nc]\s+\S+|--cpu-bind=\S+|--cpu_bind=\S+|--ntasks(?:=|\s)\S+|--cpus-per-task(?:=|\s)\S+))*\s+vasp_std", DEFAULT_VASP_SRUN_COMMAND, text)
    submit_path.write_text(text)
    submit_path.chmod(0o755)


def generate_relaxation_inputs_for_workflow(
    structure: Dict[str, Any],
    package_root: Path,
    relaxation_settings: Optional[Dict[str, Any]] = None,
    *,
    potcar_dir: str = DEFAULT_NERSC_POTCAR_DIR,
    account: str = DEFAULT_NERSC_ACCOUNT,
    queue: str = "regular",
    nodes: int = 1,
    walltime: str = "02:00:00",
    email: str = "",
) -> Dict[str, Any]:
    """Generate ``01_structure/submit_relax.sh`` as part of a full workflow package."""
    package_root = Path(package_root)
    relax_dir = package_root / "01_structure"
    relax_dir.mkdir(parents=True, exist_ok=True)
    StructureGenerator().save_structure(structure, output_dir=str(relax_dir), name="structure")

    relax_gen = RelaxationInputGenerator()
    script_gen = NERSCScriptGenerator()
    relax_files = relax_gen.write_inputs(structure, str(relax_dir))
    patch_vasp_relaxation_incar(relax_dir / "INCAR", relaxation_settings or {})
    make_potcar = write_make_potcar_script(structure, relax_dir, potcar_dir)
    for path in relax_dir.rglob("POTCAR.spec"):
        try:
            path.unlink()
        except FileNotFoundError:
            pass

    sample_label = sample_label_from_structure(structure, "web_xas_agent")
    submit = script_gen.write_script(
        str(relax_dir),
        job_name=slurm_safe_job_name(f"{sample_label}_structure_relax"),
        software="VASP",
        filename="submit_relax.sh",
        account=account,
        queue=queue,
        nodes=int(nodes),
        walltime=walltime,
        email=email.strip() or None,
    )
    patch_vasp_submit_for_nersc_cpu(Path(submit))
    return {
        "status": "success",
        "relax_folder": str(relax_dir),
        "submit": str(submit),
        "make_potcar": str(make_potcar),
        "files": sorted(str(p) for p in relax_dir.rglob("*") if p.is_file()),
        "relax_generator_result": relax_files,
    }


def prepare_single_structure_workflow_package(
    *,
    structure: Dict[str, Any],
    package_root: str | Path,
    repo_root: str | Path,
    absorber: str = "Cu",
    edge: str = "K",
    relaxation_settings: Optional[Dict[str, Any]] = None,
    account: str = DEFAULT_NERSC_ACCOUNT,
    queue: str = "regular",
    nodes: int = 1,
    walltime: str = "02:00:00",
    email: str = "",
    vasp_method: str = "PBE",
    cluster_radius: float = 6.0,
    fdmnes_method: str = "Green",
    fdmnes_scf: bool = False,
    potcar_dir: str = DEFAULT_NERSC_POTCAR_DIR,
) -> Dict[str, Any]:
    """Prepare the full web-app package in the corrected order.

    This function implements the intended UI operation:
    generate structure externally -> generate relaxation inputs internally -> add
    workflow_submit/workflow_xas/status/restart/cancel scripts.
    """
    package_root = Path(package_root).resolve()
    repo_root = Path(repo_root).resolve()
    if package_root.exists():
        # Keep user outputs outside the package root intact by only removing known
        # workflow subfolders/files that are regenerated by this operation.
        for name in ["01_structure", "workflow_submit.sh", "workflow_xas.sh", "workflow_restart.sh", "workflow_status.sh", "workflow_cancel.sh", "workflow_state.py", "workflow_manifest.json"]:
            target = package_root / name
            if target.is_dir():
                import shutil
                shutil.rmtree(target)
            elif target.exists():
                target.unlink()
    package_root.mkdir(parents=True, exist_ok=True)

    relax_result = generate_relaxation_inputs_for_workflow(
        structure,
        package_root,
        relaxation_settings=relaxation_settings or {},
        potcar_dir=potcar_dir,
        account=account,
        queue=queue,
        nodes=int(nodes),
        walltime=walltime,
        email=email,
    )
    workflow_args = Namespace(
        package_root=str(package_root),
        repo_root=str(repo_root),
        absorber=absorber,
        edge=edge,
        vasp_method=vasp_method,
        cluster_radius=float(cluster_radius),
        fdmnes_method=fdmnes_method,
        fdmnes_scf=bool(fdmnes_scf),
        potcar_dir=potcar_dir,
        account=account,
        queue=queue,
        nodes=int(nodes),
        walltime=walltime,
        email=email or "",
    )
    workflow_result = create_workflow(package_root, workflow_args)
    manifest_path = package_root / "workflow_manifest.json"
    manifest = json.loads(manifest_path.read_text()) if manifest_path.exists() else {}
    manifest["web_app_order"] = [
        "generate_structure",
        "generate_relaxation_inputs_inside_prepare_full_workflow",
        "generate_workflow_scripts",
        "upload_package",
        "remote_bash_workflow_submit",
        "refresh_workflow_state",
    ]
    manifest["relaxation"] = relax_result
    manifest_path.write_text(json.dumps(manifest, indent=2))
    return {
        "status": "success",
        "package_root": str(package_root),
        "relaxation": relax_result,
        "workflow": workflow_result,
        "submit_script": str(package_root / "workflow_submit.sh"),
        "status_script": str(package_root / "workflow_status.sh"),
        "restart_script": str(package_root / "workflow_restart.sh"),
        "cancel_script": str(package_root / "workflow_cancel.sh"),
        "state_file": str(package_root / "workflow_state.json"),
        "manifest": str(manifest_path),
    }


def workflow_remote_script_path(remote_dir: str, script_name: str) -> str:
    return str(PurePosixPath(str(remote_dir).rstrip("/")) / script_name)


def run_remote_workflow_script(client: Any, remote_dir: str, script_name: str, timeout_s: int = 120) -> Dict[str, Any]:
    """Run one generated workflow helper through the SF API command endpoint."""
    remote_dir = str(remote_dir).rstrip("/")
    script_name = str(script_name).strip() or "workflow_submit.sh"
    if script_name not in {"workflow_submit.sh", "workflow_status.sh", "workflow_restart.sh", "workflow_cancel.sh"}:
        raise ValueError(f"Unsupported workflow script: {script_name}")
    cmd = f"cd {client.shell_quote(remote_dir)} && bash {client.shell_quote(script_name)}"
    task = client.run_command(cmd)
    task_id = str(task.get("task_id") or task.get("id") or "")
    if not task_id:
        return task
    task_result = client.wait_task(task_id, timeout_s=timeout_s)
    result_json = client.task_result_json(task_result) if hasattr(client, "task_result_json") else {}
    return {
        "status": "completed",
        "remote_dir": remote_dir,
        "script": script_name,
        "task_id": task_id,
        "task": task_result,
        "result": result_json,
    }
