"""
XAS Input Generator Tool for CO2RR XAS Agent
Skill 2 Implementation
"""

import os
import json
import numpy as np
from typing import Dict, List, Tuple, Optional
from .utils import (
    ATOMIC_NUMBERS, METALS_3D, METALS_4D, METALS_5D,
    EDGE_ENERGIES, METAL_DATA,
    get_edge_for_element, get_edge_energy, contains_carbon,
    read_poscar, write_poscar, ensure_dir
)

def get_dipol_direct(structure: Dict) -> str:
    """
    Return DIPOL in direct lattice coordinates.

    VASP DIPOL expects direct coordinates. For asymmetric slabs, use the
    geometric center of the atoms, not the cell center, because vacuum is
    one-sided.
    """
    positions = np.array(structure["positions"])
    cell = np.array(structure["cell"])

    center_cart = positions.mean(axis=0)
    center_direct = np.dot(center_cart, np.linalg.inv(cell))
    center_direct = center_direct % 1.0

    return f"DIPOL = {center_direct[0]:.6f} {center_direct[1]:.6f} {center_direct[2]:.6f}"

class RelaxationInputGenerator:
    """Generate VASP relaxation inputs."""
    
    def __init__(self):
        self.potcar_map = {
            'H': 'H', 'C': 'C', 'N': 'N', 'O': 'O',
            'Fe': 'Fe_pv', 'Co': 'Co_pv', 'Ni': 'Ni_pv',
            'Cu': 'Cu_pv', 'Zn': 'Zn', 'Pd': 'Pd_pv',
            'Ag': 'Ag', 'Pt': 'Pt_pv', 'Au': 'Au',
            'Al': 'Al', 'Rh': 'Rh_pv', 'Ir': 'Ir'
        }
    
    def generate_incar(self, structure: Dict) -> str:
        """Generate INCAR for relaxation."""
        lines = [
            "# VASP INCAR for structure relaxation",
            "# Generated by CO2RR-XAS Agent",
            "",
            "# Electronic settings",
            "ENCUT = 520",
            "EDIFF = 1E-6",
            "ISMEAR = 0",
            "SIGMA = 0.05",
            "LREAL = Auto",
            "PREC = Accurate",
            "",
            "# Ionic relaxation",
            "IBRION = 2",
            "NSW = 200",
            "EDIFFG = -0.02",
            "ISIF = 2",
            "",    
            "# Dipole correction for asymmetric one-sided slab",
            "LDIPOL = .TRUE.",
            "IDIPOL = 3",
            get_dipol_direct(structure),
            "AMIN = 0.01",
            "",
            "# Spin",
            "ISPIN = 2",
            "",
            "# Output",
            "LWAVE = .FALSE.",
            "LCHARG = .FALSE.",
            "NCORE = 4",
        ]
        return "\n".join(lines)
    
    def generate_kpoints(self, structure: Dict) -> str:
        """Generate KPOINTS for relaxation."""
        cell = structure['cell']
        lengths = [np.linalg.norm(cell[i]) for i in range(3)]
        kpoints = [max(1, int(30 / l)) for l in lengths]
        # Reduce k-points in z-direction for slab
        kpoints[2] = 1
        
        lines = [
            "Automatic mesh",
            "0",
            "Gamma",
            f"  {kpoints[0]}  {kpoints[1]}  {kpoints[2]}",
            "  0  0  0"
        ]
        return "\n".join(lines)
    
    def generate_potcar_spec(self, structure: Dict) -> str:
        """Generate POTCAR specification file."""
        unique_elements = []
        for atom in structure['atoms']:
            if atom not in unique_elements:
                unique_elements.append(atom)
        
        lines = ["# POTCAR specification", "# Concatenate these POTCARs in order:"]
        for elem in unique_elements:
            potcar = self.potcar_map.get(elem, elem)
            lines.append(f"{potcar}")
        
        return "\n".join(lines)
    
    def write_inputs(self, structure: Dict, output_dir: str) -> List[str]:
        """Write all relaxation input files."""
        ensure_dir(output_dir)
        files = []
        
        # POSCAR
        poscar_path = os.path.join(output_dir, "POSCAR")
        write_poscar(
            structure['atoms'],
            structure['positions'],
            structure['cell'],
            poscar_path
        )
        files.append(poscar_path)
        
        # INCAR
        incar_path = os.path.join(output_dir, "INCAR")
        with open(incar_path, 'w') as f:
            f.write(self.generate_incar(structure))
        files.append(incar_path)
        
        # KPOINTS
        kpoints_path = os.path.join(output_dir, "KPOINTS")
        with open(kpoints_path, 'w') as f:
            f.write(self.generate_kpoints(structure))
        files.append(kpoints_path)
        
        # POTCAR.spec
        potcar_path = os.path.join(output_dir, "POTCAR.spec")
        with open(potcar_path, 'w') as f:
            f.write(self.generate_potcar_spec(structure))
        files.append(potcar_path)
        
        return files


class FEFFInputGenerator:
    """Generate FEFF input files."""
    
    def generate_input(
        self,
        structure: Dict,
        absorber: str,
        absorber_index: int = 0,
        edge: str = "K",
        radius: float = 6.0,
        scf: bool = True,
        fms: bool = True
    ) -> str:
        """Generate feff.inp content."""
        atoms = structure['atoms']
        positions = np.array(structure['positions'])
        
        # Find absorber atoms
        abs_indices = [i for i, a in enumerate(atoms) if a == absorber]
        if absorber_index >= len(abs_indices):
            absorber_index = 0
        abs_idx = abs_indices[absorber_index]
        abs_pos = positions[abs_idx]
        
        # Build cluster
        cluster_atoms = []
        cluster_positions = []
        
        for i, (atom, pos) in enumerate(zip(atoms, positions)):
            dist = np.linalg.norm(pos - abs_pos)
            if dist <= radius:
                cluster_atoms.append(atom)
                cluster_positions.append(pos - abs_pos)
        
        cluster_positions = np.array(cluster_positions)
        
        # Generate input
        lines = [
            "* FEFF input file",
            f"* Absorber: {absorber}, Edge: {edge}",
            f"* Generated by CO2RR-XAS Agent",
            "",
            f"TITLE {absorber} {edge}-edge XAS",
            "",
            f"EDGE    {edge}",
            "S02     1.0",
            "",
            "CONTROL 1 1 1 1 1 1",
            "PRINT   0 0 0 0 0 0",
            "",
        ]
        
        if scf:
            lines.extend(["SCF     5.0  0  30  0.2  3", ""])
        
        if fms:
            lines.extend([f"FMS     {radius:.1f}", ""])
        
        lines.extend([
            "XANES   4.0  0.05  0.1",
            "",
            "EXCHANGE 0 0.0 0.0 2",
            "",
            "POTENTIALS",
            "*    ipot   Z   element"
        ])
        
        # Unique elements (absorber first)
        unique_elements = [absorber]
        for atom in cluster_atoms:
            if atom not in unique_elements:
                unique_elements.append(atom)
        
        for ipot, elem in enumerate(unique_elements):
            z = ATOMIC_NUMBERS.get(elem, 1)
            lines.append(f"     {ipot}      {z}    {elem}")
        
        lines.extend(["", "ATOMS", "*    x          y          z       ipot  tag  distance"])
        
        # Sort by distance
        distances = np.linalg.norm(cluster_positions, axis=1)
        sorted_indices = np.argsort(distances)
        
        for idx in sorted_indices:
            atom = cluster_atoms[idx]
            pos = cluster_positions[idx]
            dist = distances[idx]
            ipot = unique_elements.index(atom)
            lines.append(f"     {pos[0]:10.5f} {pos[1]:10.5f} {pos[2]:10.5f}  {ipot}  {atom}  {dist:.4f}")
        
        lines.extend(["", "END"])
        
        return "\n".join(lines)
    
    def write_input(
        self,
        structure: Dict,
        output_dir: str,
        absorber: str,
        edge: str = "K",
        **kwargs
    ) -> str:
        """Write feff.inp to directory."""
        ensure_dir(output_dir)
        
        content = self.generate_input(structure, absorber, edge=edge, **kwargs)
        filepath = os.path.join(output_dir, "feff.inp")
        
        with open(filepath, 'w') as f:
            f.write(content)
        
        return filepath

class FDMNESInputGenerator:
    """Generate FDMNES input files."""

    DEFAULT_OPTIONS = {
        "Quadrupole": False,
        "Relativism": False,
        "Spinorbit": False,
        "SCF": True,
        "SCFexc": False,
        "Screening": False,
        "Full_atom": False,
        "TDDFT": False,
        "Green": False,   # False = finite difference method; True = Green multiple scattering
    }

    OPTION_ORDER = [
        "Quadrupole",
        "Relativism",
        "Spinorbit",
        "SCF",
        "SCFexc",
        "Screening",
        "Full_atom",
        "TDDFT",
        "Green",
    ]

    def _fmt_fdmnes_float(self, value: float) -> str:
        """Format values like -5. 0.2 50. for FDMNES style."""
        value = float(value)
        if value.is_integer():
            return f"{int(value)}."
        return f"{value:g}"

    def _merge_options(self, options: Optional[Dict] = None) -> Dict:
        merged = dict(self.DEFAULT_OPTIONS)
        if options:
            for key, value in options.items():
                if key in merged:
                    merged[key] = bool(value)
        return merged

    def generate_actual_input(
        self,
        structure: Dict,
        absorber: str,
        edge: str = "K",
        radius: float = 6.0,
        energy_range: Tuple[float, float, float] = (-5.0, 0.2, 50.0),
        options: Optional[Dict] = None,
        filout: Optional[str] = None,
    ) -> str:
        """
        Generate actual FDMNES input, e.g. Cu_in.txt.

        energy_range order is:
            (emin, step, emax)
        """
        atoms = structure["atoms"]
        positions = np.array(structure["positions"])
        cell = np.array(structure["cell"])

        absorber_z = ATOMIC_NUMBERS.get(absorber)
        if absorber_z is None:
            raise ValueError(f"Unknown absorber element: {absorber}")

        opts = self._merge_options(options)

        # Convert Cartesian positions to fractional coordinates.
        # This code stores lattice vectors as rows: cart = frac @ cell.
        frac_positions = np.dot(positions, np.linalg.inv(cell))
        frac_positions = frac_positions % 1.0

        # Cell parameters
        a = np.linalg.norm(cell[0])
        b = np.linalg.norm(cell[1])
        c = np.linalg.norm(cell[2])

        alpha = np.degrees(
            np.arccos(np.clip(np.dot(cell[1], cell[2]) / (b * c), -1.0, 1.0))
        )
        beta = np.degrees(
            np.arccos(np.clip(np.dot(cell[0], cell[2]) / (a * c), -1.0, 1.0))
        )
        gamma = np.degrees(
            np.arccos(np.clip(np.dot(cell[0], cell[1]) / (a * b), -1.0, 1.0))
        )

        emin, estep, emax = energy_range
        filout = filout or absorber

        lines = [
            "Filout",
            f"  {filout}",
            "",
            "Range",
            f"  {self._fmt_fdmnes_float(emin)} {self._fmt_fdmnes_float(estep)} {self._fmt_fdmnes_float(emax)}",
            "",
            "Radius",
            f"  {float(radius):.1f}",
            "",
            "Energpho",
            "",
            "Memory_save",
            "",
        ]

        for keyword in self.OPTION_ORDER:
            if opts.get(keyword, False):
                lines.extend([keyword, ""])

        lines.extend([
            "Perdew",
            "",
            "Crystal",
            f"{a:.6f} {b:.6f} {c:.6f} {alpha:.6f} {beta:.6f} {gamma:.6f}",
        ])

        for atom, frac in zip(atoms, frac_positions):
            z = ATOMIC_NUMBERS.get(atom)
            if z is None:
                raise ValueError(f"Unknown atomic number for element: {atom}")
            lines.append(f"  {z:3d} {frac[0]:.8f} {frac[1]:.8f} {frac[2]:.8f}")

        lines.extend([
            "",
            "Z_Absorber",
            f"  {absorber_z}",
            "",
            "Edge",
            f"  {edge}",
            "",
            "Convolution",
            "",
            "End",
            "",
        ])

        return "\n".join(lines)

    def generate_fdmfile(self, input_filename: str) -> str:
        """Generate driver file fdmfile.txt."""
        return f"1\n{input_filename}\n"

    def write_input(
        self,
        structure: Dict,
        output_dir: str,
        absorber: str,
        edge: str = "K",
        radius: float = 6.0,
        energy_range: Tuple[float, float, float] = (-5.0, 0.2, 50.0),
        options: Optional[Dict] = None,
    ) -> Dict[str, str]:
        """
        Write both FDMNES files:
        - fdmfile.txt
        - {absorber}_in.txt
        """
        ensure_dir(output_dir)

        input_filename = f"{absorber}_in.txt"
        input_path = os.path.join(output_dir, input_filename)
        fdmfile_path = os.path.join(output_dir, "fdmfile.txt")

        actual_input = self.generate_actual_input(
            structure=structure,
            absorber=absorber,
            edge=edge,
            radius=radius,
            energy_range=energy_range,
            options=options,
        )

        with open(input_path, "w") as f:
            f.write(actual_input)

        with open(fdmfile_path, "w") as f:
            f.write(self.generate_fdmfile(input_filename))

        return {
            "fdmfile": fdmfile_path,
            "input": input_path,
        }


class VASPXASInputGenerator:
    """Generate VASP XAS input files."""
    
    def __init__(self):
        self.potcar_map = {
            'H': 'H', 'C': 'C', 'N': 'N', 'O': 'O',
            'Fe': 'Fe_pv', 'Co': 'Co_pv', 'Ni': 'Ni_pv',
            'Cu': 'Cu_pv', 'Zn': 'Zn', 'Pd': 'Pd_pv',
            'Ag': 'Ag', 'Pt': 'Pt_pv', 'Au': 'Au'
        }
    
    def generate_incar_gw(
        self,
        structure: Dict,
        absorber: str,
        absorber_index: int = 0,
        nbands: int = None
    ) -> str:
        """Generate INCAR for GW-based XAS."""
        n_atoms = len(structure['atoms'])
        if nbands is None:
            nbands = n_atoms * 8 + 100
        
        lines = [
            "# VASP INCAR for GW-based XAS",
            f"# Absorber: {absorber}",
            "# Generated by CO2RR-XAS Agent",
            "",
            "# Electronic settings",
            "ENCUT = 400",
            "EDIFF = 1E-6",
            "ISMEAR = 0",
            "SIGMA = 0.05",
            "LREAL = .FALSE.",
            "PREC = Accurate",
            "",
            "# GW settings",
            "ALGO = GW0",
            f"NBANDS = {nbands}",
            "NOMEGA = 100",
            "LOPTICS = .TRUE.",
            "CSHIFT = 0.1",
            "",
            "# Dipole correction for asymmetric one-sided slab",
            "LDIPOL = .TRUE.",
            "IDIPOL = 3",
            get_dipol_direct(structure),
            "AMIN = 0.01",
            "",
            "# Core-level",
            "ICORELEVEL = 2",
            f"CLNT = {absorber_index + 1}",
            "CLN = 1",
            "CLL = 0",
            "CLZ = 0.5",
            "",
            "# Spin",
            "ISPIN = 2",
            "",
            "# Output",
            "LWAVE = .TRUE.",
            "LCHARG = .TRUE.",
            "NCORE = 4",
        ]
        return "\n".join(lines)
    
    def generate_incar_pbe(
        self,
        structure: Dict,
        absorber: str,
        absorber_index: int = 0,
        nbands: int = None
    ) -> str:
        """Generate INCAR for PBE-based XAS."""
        n_atoms = len(structure['atoms'])
        if nbands is None:
            nbands = n_atoms * 8 + 100
        
        lines = [
            "# VASP INCAR for PBE-based XAS",
            f"# Absorber: {absorber}",
            "# Generated by CO2RR-XAS Agent",
            "",
            "# Electronic settings",
            "ENCUT = 520",
            "EDIFF = 1E-6",
            "ISMEAR = 0",
            "SIGMA = 0.05",
            "LREAL = .FALSE.",
            "PREC = Accurate",
            f"NBANDS = {nbands}",
            "",
            "# Optics",
            "LOPTICS = .TRUE.",
            "CSHIFT = 0.1",
            "NEDOS = 2001",
            "",
            "# Dipole correction for asymmetric one-sided slab",
            "LDIPOL = .TRUE.",
            "IDIPOL = 3",
            get_dipol_direct(structure),
            "AMIN = 0.01",
            "",
            "# Core-level",
            "ICORELEVEL = 2",
            f"CLNT = {absorber_index + 1}",
            "CLN = 1",
            "CLL = 0",
            "CLZ = 0.5",
            "",
            "# Spin",
            "ISPIN = 2",
            "",
            "# Output",
            "LWAVE = .TRUE.",
            "LCHARG = .TRUE.",
            "NCORE = 4",
        ]
        return "\n".join(lines)
    
    def generate_kpoints(self, structure: Dict) -> str:
        """Generate KPOINTS for XAS."""
        cell = structure['cell']
        lengths = [np.linalg.norm(cell[i]) for i in range(3)]
        kpoints = [max(1, int(25 / l)) for l in lengths]
        kpoints[2] = 1  # Slab
        
        lines = [
            "Automatic mesh",
            "0",
            "Gamma",
            f"  {kpoints[0]}  {kpoints[1]}  {kpoints[2]}",
            "  0  0  0"
        ]
        return "\n".join(lines)
    
    def generate_potcar_spec(self, structure: Dict) -> str:
        """Generate POTCAR specification."""
        unique_elements = []
        for atom in structure['atoms']:
            if atom not in unique_elements:
                unique_elements.append(atom)
        
        lines = ["# POTCAR specification"]
        for elem in unique_elements:
            potcar = self.potcar_map.get(elem, elem)
            lines.append(potcar)
        
        return "\n".join(lines)
    
    def write_inputs(
        self,
        structure: Dict,
        output_dir: str,
        absorber: str,
        method: str = "PBE",
        **kwargs
    ) -> List[str]:
        """Write VASP XAS input files."""
        ensure_dir(output_dir)
        files = []
        
        # POSCAR
        poscar_path = os.path.join(output_dir, "POSCAR")
        write_poscar(
            structure['atoms'],
            structure['positions'],
            structure['cell'],
            poscar_path,
            selective_dynamics=False
        )
        files.append(poscar_path)
        
        # INCAR
        incar_path = os.path.join(output_dir, "INCAR")
        if method.upper() == "GW":
            incar_content = self.generate_incar_gw(structure, absorber, **kwargs)
        else:
            incar_content = self.generate_incar_pbe(structure, absorber, **kwargs)
        
        with open(incar_path, 'w') as f:
            f.write(incar_content)
        files.append(incar_path)
        
        # KPOINTS
        kpoints_path = os.path.join(output_dir, "KPOINTS")
        with open(kpoints_path, 'w') as f:
            f.write(self.generate_kpoints(structure))
        files.append(kpoints_path)
        
        # POTCAR.spec
        potcar_path = os.path.join(output_dir, "POTCAR.spec")
        with open(potcar_path, 'w') as f:
            f.write(self.generate_potcar_spec(structure))
        files.append(potcar_path)
        
        return files


class NERSCScriptGenerator:
    """Generate NERSC SLURM submission scripts."""
    
    def generate_script(
        self,
        job_name: str,
        software: str,
        account: str = "m5268",
        queue: str = "regular",
        nodes: int = 2,
        walltime: str = "8:00:00",
        email: Optional[str] = None
    ) -> str:
        """Generate SLURM submission script."""
        lines = [
            "#!/bin/bash",
            f"#SBATCH -J {job_name}",
            f"#SBATCH -q {queue}",
            f"#SBATCH -A {account}",
            "#SBATCH -C cpu",
            f"#SBATCH -N {nodes}",
            f"#SBATCH -t {walltime}",
        ]
        
        if email:
            lines.extend([
                "#SBATCH --mail-type=ALL",
                f"#SBATCH --mail-user={email}"
            ])
        
        lines.append("")
        
        # Software-specific commands
        if software.upper() == "VASP":
            lines.extend([
                "module load vasp/6.4.3-cpu",
                "export OMP_NUM_THREADS=2",
                "export OMP_PLACES=threads",
                "export OMP_PROC_BIND=spread",
                "",
                "srun vasp_std"
            ])
        elif software.upper() == "FEFF":
            lines.extend([
                "module load feff/10.0",
                "",
                "feff"
            ])
        elif software.upper() == "FDMNES":
            lines.extend([
                "module load fdmnes/2023",
                "",
                "fdmnes < fdmfile.txt"
            ])
        
        return "\n".join(lines)
    
    def write_script(
        self,
        output_dir: str,
        job_name: str,
        software: str,
        filename: str = "submit.sh",
        **kwargs
    ) -> str:
        """Write submission script to file."""
        ensure_dir(output_dir)
        
        content = self.generate_script(job_name, software, **kwargs)
        filepath = os.path.join(output_dir, filename)
        
        with open(filepath, 'w') as f:
            f.write(content)
        
        # Make executable
        os.chmod(filepath, 0o755)
        
        return filepath


class XASInputGenerator:
    """
    Main XAS Input Generator combining all methods.
    """
    
    def __init__(self):
        self.relax_gen = RelaxationInputGenerator()
        self.feff_gen = FEFFInputGenerator()
        self.fdmnes_gen = FDMNESInputGenerator()
        self.vasp_gen = VASPXASInputGenerator()
        self.script_gen = NERSCScriptGenerator()
    
    def determine_absorbers(self, structure: Dict) -> List[Dict]:
        """
        Determine all absorbers and their edges for a structure.
        
        Returns:
            List of dicts with 'element', 'edge', 'vasp_allowed'
        """
        absorbers = []
        seen = set()
        
        # Get unique elements
        for atom in structure['atoms']:
            if atom in seen:
                continue
            seen.add(atom)
            
            edge, vasp_allowed = get_edge_for_element(atom)
            
            # Only include metals and C
            if atom in METALS_3D + METALS_4D + METALS_5D or atom == 'C':
                absorbers.append({
                    'element': atom,
                    'edge': edge,
                    'vasp_allowed': vasp_allowed
                })
        
        return absorbers

    def generate_all_inputs(
        self,
        structure: Dict,
        output_dir: str,
        nersc_account: str = "m5268",
        nersc_queue: str = "regular",
        nersc_nodes: int = 2,
        nersc_walltime: str = "8:00:00",
        email: Optional[str] = None,
        cluster_radius: float = 6.0,
        fdmnes_options: Optional[Dict] = None,
        fdmnes_energy_range: Tuple[float, float, float] = (-5.0, 0.2, 50.0),
        edge_override: Optional[str] = None,
    ) -> Dict:
        """
        Generate all XAS inputs for a structure.
        
        Creates:
        - relax/ folder with VASP relaxation
        - xas/{Element}_{Edge}_edge/{Method}/ folders
        
        Returns:
            Dictionary with all generated file paths
        """
        results = {
            'relax': {},
            'xas': {}
        }
        
        # 1. Generate relaxation inputs
        relax_dir = os.path.join(output_dir, "relax")
        relax_files = self.relax_gen.write_inputs(structure, relax_dir)
        
        # Relaxation submit script
        meta = structure.get('metadata', {})
        job_base = f"{meta.get('element', meta.get('element1', 'struct'))}"
        if meta.get('adsorbate'):
            job_base += f"_{meta['adsorbate']}"
        
        relax_script = self.script_gen.write_script(
            relax_dir,
            f"{job_base}_relax",
            "VASP",
            "submit_relax.sh",
            account=nersc_account,
            queue=nersc_queue,
            nodes=nersc_nodes,
            walltime=nersc_walltime,
            email=email
        )
        
        results['relax'] = {
            'files': relax_files,
            'submit_script': relax_script
        }
        
        # 2. Determine absorbers
        absorbers = self.determine_absorbers(structure)
        
        # 3. Generate XAS inputs for each absorber
        for abs_info in absorbers:
            element = abs_info['element']
            edge = abs_info['edge']
            vasp_allowed = abs_info['vasp_allowed']

            if edge_override:
                edge = edge_override
                vasp_allowed = vasp_allowed and edge == "K"
            
            edge_key = f"{element}_{edge}_edge"
            edge_dir = os.path.join(output_dir, "xas", edge_key)
            
            results['xas'][edge_key] = {}
            

            # FDMNES: one folder only.
            # Finite difference if Green=False; multiple scattering if Green=True.
            fdmnes_options = fdmnes_options or FDMNESInputGenerator.DEFAULT_OPTIONS
            fdmnes_method = "green" if fdmnes_options.get("Green", False) else "fdm"

            fdmnes_dir = os.path.join(edge_dir, "FDMNES")
            fdmnes_files = self.fdmnes_gen.write_input(
                structure=structure,
                output_dir=fdmnes_dir,
                absorber=element,
                edge=edge,
                radius=cluster_radius,
                energy_range=fdmnes_energy_range,
                options=fdmnes_options,
            )

            fdmnes_script = self.script_gen.write_script(
                fdmnes_dir,
                f"{job_base}_{element}_{edge}_fdmnes_{fdmnes_method}",
                "FDMNES",
                account=nersc_account,
                queue=nersc_queue,
                email=email,
            )

            results["xas"][edge_key]["FDMNES"] = {
                "method": "green_multiple_scattering" if fdmnes_options.get("Green", False) else "finite_difference",
                "fdmfile": fdmnes_files["fdmfile"],
                "input": fdmnes_files["input"],
                "submit": fdmnes_script,
                "options": fdmnes_options,
                "radius_angstrom": cluster_radius,
                "energy_range": fdmnes_energy_range,
            }
            
            # FEFF
            feff_dir = os.path.join(edge_dir, "FEFF")
            feff_file = self.feff_gen.write_input(
                structure, feff_dir, element, edge=edge,
                radius=cluster_radius
            )
            feff_script = self.script_gen.write_script(
                feff_dir, f"{job_base}_{element}_{edge}_feff", "FEFF",
                account=nersc_account, queue=nersc_queue, email=email
            )
            results['xas'][edge_key]['FEFF'] = {
                'input': feff_file,
                'submit': feff_script
            }
            
            # VASP (only for K-edge)
            if vasp_allowed:
                # VASP_GW
                gw_dir = os.path.join(edge_dir, "VASP_GW")
                gw_files = self.vasp_gen.write_inputs(
                    structure, gw_dir, element, method="GW"
                )
                gw_script = self.script_gen.write_script(
                    gw_dir, f"{job_base}_{element}_{edge}_gw", "VASP",
                    account=nersc_account, queue=nersc_queue,
                    nodes=nersc_nodes, walltime=nersc_walltime, email=email
                )
                results['xas'][edge_key]['VASP_GW'] = {
                    'files': gw_files,
                    'submit': gw_script
                }
                
                # VASP_PBE
                pbe_dir = os.path.join(edge_dir, "VASP_PBE")
                pbe_files = self.vasp_gen.write_inputs(
                    structure, pbe_dir, element, method="PBE"
                )
                pbe_script = self.script_gen.write_script(
                    pbe_dir, f"{job_base}_{element}_{edge}_pbe", "VASP",
                    account=nersc_account, queue=nersc_queue,
                    nodes=nersc_nodes, walltime=nersc_walltime, email=email
                )
                results['xas'][edge_key]['VASP_PBE'] = {
                    'files': pbe_files,
                    'submit': pbe_script
                }
        
        return results


# =============================================================================
# Skill Interface Function
# =============================================================================

def execute_xas_input_generation(
    structure_file: str,
    output_dir: str,
    nersc_account: str = "m5268",
    nersc_queue: str = "regular",
    nersc_nodes: int = 2,
    nersc_walltime: str = "8:00:00",
    email: Optional[str] = None,
    cluster_radius: float = 6.0,
    fdmnes_options: Optional[Dict] = None,
    fdmnes_energy_range: Tuple[float, float, float] = (-5.0, 0.2, 50.0),
    edge_override: Optional[str] = None,
    structure_metadata: Optional[Dict] = None
) -> Dict:
    """
    Execute Skill 2: XAS Input Generation
    
    Args:
        structure_file: Path to POSCAR/CONTCAR file
        output_dir: Output directory
        nersc_account: NERSC allocation account
        nersc_queue: SLURM queue
        nersc_nodes: Number of nodes
        nersc_walltime: Wall time
        email: Email for notifications
        cluster_radius: Cluster radius for FEFF/FDMNES
        structure_metadata: Optional metadata dict
        
    Returns:
        Dictionary with results and file paths
    """
    # Read structure
    structure = read_poscar(structure_file)
    
    # Add metadata if provided
    if structure_metadata:
        structure['metadata'] = structure_metadata
    elif 'metadata' not in structure:
        structure['metadata'] = {}
    
    # Generate all inputs
    generator = XASInputGenerator()
    results = generator.generate_all_inputs(
        structure=structure,
        output_dir=output_dir,
        nersc_account=nersc_account,
        nersc_queue=nersc_queue,
        nersc_nodes=nersc_nodes,
        nersc_walltime=nersc_walltime,
        email=email,
        fdmnes_options=fdmnes_options,
        fdmnes_energy_range=fdmnes_energy_range,
        edge_override=edge_override,
        cluster_radius=cluster_radius
    )
    
    results['status'] = 'success'
    results['structure_file'] = structure_file
    results['output_dir'] = output_dir
    
    return results